-- The four AEAT rectificativa fields on the immutable registro de facturación (piece 2 of the
-- fiscal sequence). docs/superpowers/plans/2026-08-02-rectificativas.md §2.2.
--
-- All NULL on an ordinary alta and on an anulación; set on a registro de alta whose TipoFactura is
-- R1–R5. `jsonb`, not `text`, is safe for the three structured fields because NONE of the four is
-- a huella input — huella.ts hashes 8 named fields, none among these — so they are only ever
-- re-serialised into XML, never digested (identical to `desglose`/`sistema_informatico`). A field
-- that WERE hashed would need `text` for byte-identity, like `cuota_total`/`importe_total`.
--
--   registros_tipo_rectificativa_ck       — the value domain {S, I} (or NULL), mirrors
--                                           registros_entorno_ck.
--   registros_tipo_factura_rectificativa_ck — defense-in-depth for AEAT rule 1115: a
--                                           tipo_rectificativa may only sit on an R1–R5 TipoFactura.
--                                           Rule 1114 (R-type ⇒ tipo_rectificativa present) stays at
--                                           the app layer (validate.ts), tipo_factura being nullable.
--
-- Immutability and RLS carry automatically: 0001_registros_inmutables.sql REVOKEs/GRANTs, the
-- row/statement reject_mutation triggers and the tenant-isolation policy are all TABLE-LEVEL,
-- covering any column with no privilege/trigger/policy DDL here — the same receipt
-- 0009_registro_entorno relied on. NULLABLE with no backfill (pre-production, no deployed data).
--
-- Generated by plain `drizzle-kit generate` against ./src/schema/registros.ts, keeping
-- drizzle/meta/0010_snapshot.json accurate — a --custom migration on this already-tracked table
-- would leave the snapshot missing these columns and the next plain `generate` would re-propose
-- them (the 0009 note on --custom-vs-plain on an already-tracked table).
ALTER TABLE "registros_facturacion" ADD COLUMN "tipo_rectificativa" text;--> statement-breakpoint
ALTER TABLE "registros_facturacion" ADD COLUMN "facturas_rectificadas" jsonb;--> statement-breakpoint
ALTER TABLE "registros_facturacion" ADD COLUMN "facturas_sustituidas" jsonb;--> statement-breakpoint
ALTER TABLE "registros_facturacion" ADD COLUMN "importe_rectificacion" jsonb;--> statement-breakpoint
ALTER TABLE "registros_facturacion" ADD CONSTRAINT "registros_tipo_rectificativa_ck" CHECK ("registros_facturacion"."tipo_rectificativa" is null or "registros_facturacion"."tipo_rectificativa" in ('S', 'I'));--> statement-breakpoint
ALTER TABLE "registros_facturacion" ADD CONSTRAINT "registros_tipo_factura_rectificativa_ck" CHECK ("registros_facturacion"."tipo_rectificativa" is null or ("registros_facturacion"."tipo_factura" is not null and "registros_facturacion"."tipo_factura" ~ '^R[1-5]$'));