import { makeT, registerCatalogue, registerCodeMessages } from "@waitron/dashboard-kit";
const en = {
  "nav.images": "Image library",
  "image.upload": "Upload photo",
  "image.duplicate_reused": "Existing photo reused:",
  "image.duplicate_metadata_kept": "Its name is unchanged.",
  "image.edit": "Edit image",
  "action.edit": "Edit",
  "image.name": "Name",
  "image.preview": "Selected photo preview",
  "image.file": "Photo",
  "image.search": "Search images",
  "image.sort": "Sort by",
  "image.direction": "Order",
  "image.oldest_first": "Oldest first",
  "image.newest_first": "Newest first",
  "image.name_ascending": "A–Z",
  "image.name_descending": "Z–A",
  "image.relevance": "Relevance",
  "image.date": "Date",
  "image.name_sort": "Name",
  "image.save": "Save",
  "image.cancel": "Cancel",
  "image.delete": "Delete",
  "image.select": "Use image",
  "image.empty": "No images found.",
  "image.required": "This field is required.",
  "image.file_required": "Choose a photo to upload.",
  "image.fix_fields": "Correct the highlighted fields to continue.",
  "image.load_error": "The image library could not be loaded.",
  "image.save_error": "The image could not be saved.",
  "image.delete_error": "The image could not be deleted.",
  "image.confirm": "Delete this image?",
  "image.confirm_help": "This permanently removes the photo and its translations.",
  "image.in_use": "This image is still in use. Remove these uses before deleting it.",
  "image.close": "Close",
  "image.previous": "Previous",
  "image.next": "Next",
  "image.page": "Images",
  "image.default": "Default",
  "image.disabled_product": "Disabled product",
  "image.published_menu": "Published menu",
  "image.scheduled_menu": "Scheduled menu",
  "image.receipt_logo": "Receipt logo",
  "image.retry": "Try again",
  "image.preview_open": "Preview",
  "image.uses": "Where it is used",
  "image.no_uses": "Not used anywhere yet.",
  "image.uses_loading": "Looking up where it is used…",
  "image.uses_error": "Could not look up where this image is used.",
} as const;
const es: Record<keyof typeof en, string> = {
  "nav.images": "Biblioteca de imágenes",
  "image.upload": "Subir foto",
  "image.duplicate_reused": "Se ha reutilizado la foto existente:",
  "image.duplicate_metadata_kept": "Su nombre no ha cambiado.",
  "image.edit": "Editar imagen",
  "action.edit": "Editar",
  "image.name": "Nombre",
  "image.preview": "Vista previa de la foto seleccionada",
  "image.file": "Foto",
  "image.search": "Buscar imágenes",
  "image.sort": "Ordenar por",
  "image.direction": "Orden",
  "image.oldest_first": "Más antiguas primero",
  "image.newest_first": "Más recientes primero",
  "image.name_ascending": "A–Z",
  "image.name_descending": "Z–A",
  "image.relevance": "Relevancia",
  "image.date": "Fecha",
  "image.name_sort": "Nombre",
  "image.save": "Guardar",
  "image.cancel": "Cancelar",
  "image.delete": "Eliminar",
  "image.select": "Usar imagen",
  "image.empty": "No se encontraron imágenes.",
  "image.required": "Este campo es obligatorio.",
  "image.file_required": "Elige una foto para subir.",
  "image.fix_fields": "Corrige los campos marcados para continuar.",
  "image.load_error": "No se pudo cargar la biblioteca de imágenes.",
  "image.save_error": "No se pudo guardar la imagen.",
  "image.delete_error": "No se pudo eliminar la imagen.",
  "image.confirm": "¿Eliminar esta imagen?",
  "image.confirm_help": "La foto y sus traducciones se eliminarán permanentemente.",
  "image.in_use": "Esta imagen todavía está en uso. Elimina estos usos antes de borrarla.",
  "image.close": "Cerrar",
  "image.previous": "Anterior",
  "image.next": "Siguiente",
  "image.page": "Imágenes",
  "image.default": "Predeterminado",
  "image.disabled_product": "Producto deshabilitado",
  "image.published_menu": "Carta publicada",
  "image.scheduled_menu": "Carta programada",
  "image.receipt_logo": "Logotipo del recibo",
  "image.retry": "Reintentar",
  "image.preview_open": "Vista previa",
  "image.uses": "Dónde se usa",
  "image.no_uses": "Todavía no se usa en ningún sitio.",
  "image.uses_loading": "Buscando dónde se usa…",
  "image.uses_error": "No se pudo consultar dónde se usa esta imagen.",
};
export const MEDIA_STRINGS = { en, es };
registerCatalogue(MEDIA_STRINGS);
registerCodeMessages({
  "image.invalid_metadata": {
    en: "Check the image names.",
    es: "Revisa los nombres de la imagen.",
  },
  "image.translation_required": {
    en: "Enter a name in the default language.",
    es: "Introduce un nombre en el idioma predeterminado.",
  },
  "image.in_use": { en: en["image.in_use"], es: es["image.in_use"] },
  "image.too_large": {
    en: "The photo file is too large. Export a smaller copy and try again.",
    es: "El archivo de la foto es demasiado grande. Exporta una copia más pequeña e inténtalo de nuevo.",
  },
  "image.invalid_file": {
    en: "The photo could not be read. It may be damaged, so try exporting it again.",
    es: "No se pudo leer la foto. Puede que esté dañada, así que prueba a exportarla de nuevo.",
  },
  "image.too_many_pixels": {
    en: "The photo has too many pixels. Export a smaller copy and try again.",
    es: "La foto tiene demasiados píxeles. Exporta una copia más pequeña e inténtalo de nuevo.",
  },
});
export const t = makeT<keyof typeof en>();
