import { makeT, registerCatalogue, registerCodeMessages } from "@waitron/dashboard-kit";
const en = {
  "nav.images": "Image library",
  "image.upload": "Upload photo",
  "image.duplicate_reused": "Existing photo reused:",
  "image.duplicate_metadata_kept": "Its name, alt text and labels are unchanged.",
  "image.edit": "Edit image",
  "image.name": "Name",
  "image.alt": "Alt text",
  "image.labels": "Labels",
  "image.labels_help": "Separate labels with commas. New labels are added when you save.",
  "image.file": "Photo",
  "image.search": "Search images",
  "image.filter_label": "Filter by label",
  "image.all_labels": "All labels",
  "image.sort": "Sort by",
  "image.direction": "Order",
  "image.oldest_first": "Oldest first",
  "image.newest_first": "Newest first",
  "image.name_ascending": "A–Z",
  "image.name_descending": "Z–A",
  "image.relevance": "Relevance",
  "image.date": "Date",
  "image.name_sort": "Name",
  "image.save": "Save",
  "image.cancel": "Cancel",
  "image.delete": "Delete",
  "image.select": "Use image",
  "image.empty": "No images found.",
  "image.problem": "There is a problem with this form",
  "image.required": "This field is required.",
  "image.file_required": "Choose a photo to upload.",
  "image.load_error": "The image library could not be loaded.",
  "image.save_error": "The image could not be saved.",
  "image.delete_error": "The image could not be deleted.",
  "image.confirm": "Delete this image?",
  "image.confirm_help": "This permanently removes the photo and its translations.",
  "image.in_use": "This image is still in use. Remove these uses before deleting it.",
  "image.close": "Close",
  "image.previous": "Previous",
  "image.next": "Next",
  "image.page": "Images",
  "image.default": "Default",
  "image.inactive": "Inactive product",
  "image.retry": "Try again",
} as const;
const es: Record<keyof typeof en, string> = {
  "nav.images": "Biblioteca de imágenes",
  "image.upload": "Subir foto",
  "image.duplicate_reused": "Se ha reutilizado la foto existente:",
  "image.duplicate_metadata_kept": "Su nombre, texto alternativo y etiquetas no han cambiado.",
  "image.edit": "Editar imagen",
  "image.name": "Nombre",
  "image.alt": "Texto alternativo",
  "image.labels": "Etiquetas",
  "image.labels_help": "Separa las etiquetas con comas. Las nuevas etiquetas se añaden al guardar.",
  "image.file": "Foto",
  "image.search": "Buscar imágenes",
  "image.filter_label": "Filtrar por etiqueta",
  "image.all_labels": "Todas las etiquetas",
  "image.sort": "Ordenar por",
  "image.direction": "Orden",
  "image.oldest_first": "Más antiguas primero",
  "image.newest_first": "Más recientes primero",
  "image.name_ascending": "A–Z",
  "image.name_descending": "Z–A",
  "image.relevance": "Relevancia",
  "image.date": "Fecha",
  "image.name_sort": "Nombre",
  "image.save": "Guardar",
  "image.cancel": "Cancelar",
  "image.delete": "Eliminar",
  "image.select": "Usar imagen",
  "image.empty": "No se encontraron imágenes.",
  "image.problem": "Hay un problema con este formulario",
  "image.required": "Este campo es obligatorio.",
  "image.file_required": "Elige una foto para subir.",
  "image.load_error": "No se pudo cargar la biblioteca de imágenes.",
  "image.save_error": "No se pudo guardar la imagen.",
  "image.delete_error": "No se pudo eliminar la imagen.",
  "image.confirm": "¿Eliminar esta imagen?",
  "image.confirm_help": "La foto y sus traducciones se eliminarán permanentemente.",
  "image.in_use": "Esta imagen todavía está en uso. Elimina estos usos antes de borrarla.",
  "image.close": "Cerrar",
  "image.previous": "Anterior",
  "image.next": "Siguiente",
  "image.page": "Imágenes",
  "image.default": "Predeterminado",
  "image.inactive": "Producto inactivo",
  "image.retry": "Reintentar",
};
export const MEDIA_STRINGS = { en, es };
registerCatalogue(MEDIA_STRINGS);
registerCodeMessages({
  "image.invalid_metadata": {
    en: "Check the image names, alt text and labels.",
    es: "Revisa los nombres, el texto alternativo y las etiquetas.",
  },
  "image.translation_required": {
    en: "Enter a name and alt text in the default language.",
    es: "Introduce un nombre y texto alternativo en el idioma predeterminado.",
  },
  "image.in_use": { en: en["image.in_use"], es: es["image.in_use"] },
});
export const t = makeT<keyof typeof en>();
