export const CORE_CONFIGURATION_TRANSFER = {
  kind: "tables",
  tables: [
    { name: "catalogues" },
    { name: "kitchen_stations", locationColumns: ["location_id"] },
    { name: "kitchen_courses", locationColumns: ["location_id"] },
    { name: "categories" },
    { name: "products" },
    { name: "option_groups" },
    { name: "option_group_items" },
    { name: "product_option_groups" },
    { name: "location_catalogues", locationColumns: ["location_id"] },
    { name: "ingredients" },
    { name: "recipe_lines" },
    { name: "canvases" },
    { name: "device_profiles" },
    { name: "floor_zones", locationColumns: ["location_id"] },
    { name: "table_service_statuses" },
    {
      name: "dining_tables",
      locationColumns: ["location_id"],
      omit: ["tab_id"],
    },
    {
      name: "print_agents",
      locationColumns: ["location_id"],
      omit: ["token_hash", "last_seen_at"],
      reconnect: true,
    },
    {
      name: "printers",
      locationColumns: ["location_id"],
      omit: ["poll_token_hash"],
      reconnect: true,
    },
    { name: "station_printers" },
    { name: "tenant_themes" },
    { name: "tenant_receipts" },
  ],
} as const;
