// Seed both demo menus in the caller's transaction and return the image-to-product map.
// The caller supplies the location; this module resolves the kitchen stations.

import { sql } from "drizzle-orm";
import { kitchenStations, type Transaction } from "@waitron/db";
import { preparationRoutes } from "@waitron/venue-service";
import {
  addCatalogueToLocation,
  assignCatalogueToLocation,
  createCatalogue,
  createCategory,
  createMenuItem,
  createMenuSection,
  createProduct,
  createUnit,
  replaceProductCategories,
  setProductVariants,
  writeContentLanguages,
} from "@waitron/catalogue";
import {
  CASA_DELGADO,
  DELI_TAKEAWAY,
  MENU_DEL_DIA,
  type SeedCatalogue,
  type SeedLocale,
} from "./menu.js";

export interface SeedCataloguesInput {
  /** The provisioned venue's location — the default/accessible catalogue assignment target, and the
   * location whose "Cocina" station is looked up and whose "Barra" station is created. */
  locationId: string;
  /** Which of the two authored locales each catalogue/category/product is created under. */
  locale: SeedLocale;
}

export interface SeedCataloguesResult {
  /** image basename → created product id, for Task 9's media attach and the sales generator. Every
   * seeded product appears exactly once (the menu's image basenames are unique across both menus). */
  productsByImage: Map<string, string>;
  menuItemsByProduct: Map<string, string>;
  menuIds: { restaurant: string; lunch: string; deli: string };
}

/** The logical routing targets a seed category names, mapped to their concrete `kitchen_stations.id`. */
type StationIds = Record<"kitchen" | "bar" | "deli", string> & {
  upstairsBar: string;
};

/** Resolve the location's provisioned Cocina station and create its non-default Barra station. */
async function resolveStationIds(tx: Transaction, locationId: string): Promise<StationIds> {
  const { rows: cocina } = await tx.execute<{ id: string }>(sql`
    select id from kitchen_stations
    where location_id = ${locationId} and name = 'Cocina'
    limit 1`);
  const kitchen = cocina[0]?.id;
  if (kitchen === undefined) {
    throw new Error(`seedCatalogues: no "Cocina" station found for location ${locationId}`);
  }
  await tx.execute(sql`
    update kitchen_stations set name = 'Kitchen'
    where id = ${kitchen}`);
  // Seed scripts have no management session, so insert the non-default stations directly — through
  // the table definition, because `kitchen_stations.id` and `created_at` are generated by the insert
  // BUILDER and a raw insert omitting them is refused `NOT NULL constraint failed`.
  const [bar, upstairsBar, deli] = await tx
    .insert(kitchenStations)
    .values(
      [
        { name: "Downstairs bar", displayOrder: 1 },
        { name: "Upstairs bar", displayOrder: 2 },
        { name: "Deli counter", displayOrder: 3 },
      ].map(({ name, displayOrder }) => ({
        locationId,
        name,
        displayOrder,
        isDefault: false,
        active: true,
      })),
    )
    .returning({ id: kitchenStations.id });
  if (bar === undefined || upstairsBar === undefined || deli === undefined) {
    throw new Error(
      `seedCatalogues: failed to create the demo stations for location ${locationId}`,
    );
  }
  return { kitchen, bar: bar.id, upstairsBar: upstairsBar.id, deli: deli.id };
}

/**
 * Seed both demo menus onto `locationId` in the caller's transaction, routing each category to
 * its KDS station, setting Casa Delgado as the location DEFAULT and Menú del Día as an accessible
 * second menu. Returns the image→productId map for the downstream media/sales steps.
 */
export async function seedCatalogues(
  tx: Transaction,
  { locationId, locale }: SeedCataloguesInput,
): Promise<SeedCataloguesResult> {
  const stationIds = await resolveStationIds(tx, locationId);
  await writeContentLanguages(tx, {
    defaultLanguage: locale,
    languages: locale === "en" ? ["en", "es"] : ["es", "en"],
  });
  const productsByImage = new Map<string, string>();
  const menuItemsByProduct = new Map<string, string>();
  const categoriesByEnglishName = new Map<string, string>();

  const { rows: provisionedMenus } = await tx.execute<{ id: string }>(sql`
    select default_menu_id as id from zone_service_policies
    where location_id = ${locationId} and is_counter_default
      and default_menu_id is not null
    limit 1`);

  const seedOne = async (data: SeedCatalogue, existingMenuId?: string): Promise<string> => {
    const catalogue =
      existingMenuId === undefined
        ? await createCatalogue(tx, { name: data.name[locale] })
        : { id: existingMenuId };
    if (existingMenuId !== undefined) {
      await tx.execute(sql`
        update catalogues set name = ${data.name[locale]}
        where id = ${existingMenuId}`);
    }
    for (const [categoryIndex, cat] of data.categories.entries()) {
      const category = await createCategory(tx, { name: cat.name });
      categoriesByEnglishName.set(cat.name.en, category.id);
      if (cat.station !== null) {
        // The create op takes no station; set the route with a parameterised update. Both the id and
        // the category id are bound params.
        await tx.execute(
          sql`update categories set station_id = ${stationIds[cat.station]} where id = ${category.id}`,
        );
      }
      await tx.insert(preparationRoutes).values({
        locationId,
        categoryId: category.id,
        stationId: cat.station === null ? null : stationIds[cat.station],
        noPreparation: cat.station === null,
      });
      const section = await createMenuSection(tx, {
        menuId: catalogue.id,
        name: cat.name,
        displayOrder: categoryIndex,
      });
      for (const [productIndex, product] of cat.products.entries()) {
        const unitId = product.unit
          ? (
              await createUnit(
                tx,
                {
                  name: product.unit.name,
                  precision: product.unit.precision,
                  abbreviation: product.unit.abbreviation,
                },
                locale,
              )
            ).id
          : undefined;
        const created = await createProduct(tx, {
          catalogueId: catalogue.id,
          categoryId: category.id,
          // The staff-facing name is the authored short label where the menu gives one, so the demo
          // shows a different string from the customer-facing name on every screen bound to the staff
          // name. Where the menu gives none the two are the same word anyway, and it falls back to the
          // seeded locale's entry. The customer-facing map keeps both locales, so a receipt in the
          // venue's invoice locale reads the authored translation.
          name: product.staffName ?? product.customerName[locale],
          customerName: product.customerName,
          description: product.description,
          kitchenName: product.kitchenName,
          dietaryDeclarations: product.dietaryDeclarations,
          ...(unitId === undefined ? { pricingUnit: product.pricingUnit } : { unitId }),
          unitPrice: product.unitPrice,
          vatClass: product.vatClass,
        });
        const menuItem = await createMenuItem(tx, {
          menuId: catalogue.id,
          productId: created.id,
          sectionId: section.id,
          grossPrice: product.unitPrice,
          displayOrder: productIndex,
        });
        menuItemsByProduct.set(created.id, menuItem.id);
        if (product.variants?.length) {
          await setProductVariants(
            tx,
            created.id,
            product.variants.map((variant) => ({
              name: variant.staffName ?? variant.customerName[locale],
              customerName: variant.customerName,
              kitchenName: variant.kitchenName ?? null,
              image: null,
              unitPrice: variant.unitPrice,
              available: variant.available,
            })),
            locale,
          );
        }
        if (productsByImage.has(product.image)) {
          throw new Error(
            `demo-seed: duplicate image basename '${product.image}' — image basenames must be unique across the menu`,
          );
        }
        productsByImage.set(product.image, created.id);
      }
    }
    return catalogue.id;
  };

  const casaId = await seedOne(CASA_DELGADO, provisionedMenus[0]?.id);
  const diaId = await seedOne(MENU_DEL_DIA);
  const deliId = await seedOne(DELI_TAKEAWAY);

  const coffeeId = productsByImage.get("cafe-solo.png");
  const drinksId = categoriesByEnglishName.get("Drinks");
  if (coffeeId === undefined || drinksId === undefined)
    throw new Error("demo-seed: Coffee or Drinks was not created");
  const hotDrinks = await createCategory(tx, {
    name: { en: "Hot drinks", es: "Bebidas calientes" },
  });
  await replaceProductCategories(tx, coffeeId, {
    categoryIds: [drinksId, hotDrinks.id],
    primaryCategoryId: drinksId,
  });

  const negroniId = productsByImage.get("negroni.png");
  if (negroniId === undefined) throw new Error("demo-seed: Negroni product was not created");
  const cocktailSection = await createMenuSection(tx, {
    menuId: diaId,
    name: { en: "Cocktails", es: "Cócteles" },
    displayOrder: MENU_DEL_DIA.categories.length,
  });
  await createMenuItem(tx, {
    menuId: diaId,
    productId: negroniId,
    sectionId: cocktailSection.id,
    grossPrice: "9.00",
    displayOrder: 0,
  });

  await assignCatalogueToLocation(tx, locationId, casaId);
  await addCatalogueToLocation(tx, locationId, diaId);
  await addCatalogueToLocation(tx, locationId, deliId);

  return {
    productsByImage,
    menuItemsByProduct,
    menuIds: { restaurant: casaId, lunch: diaId, deli: deliId },
  };
}
