/**
 * app_user's table privileges. Letters: S=SELECT I=INSERT U=UPDATE D=DELETE T=TRUNCATE. The
 * matrix carries the base grants; the four `sync_*` outbox tables are gone (swap S5). The design is
 * docs/superpowers/specs/2026-09-05-drop-rls-squash-and-outbox-deletion-design.md §1. A
 * deliberate grant change edits this file in the same commit, with the reason in the message.
 * Runnable receipts: scripts/schema-equivalence.md describes the dump/ACL comparison, and
 * privileges.test.ts reads every table's privileges back from the live catalog.
 *
 * has_table_privilege measures table grants only: UPDATE(next_number) on invoice_series does not
 * produce a U here. The suite beside this file guards the column privileges that need a standing
 * check; scripts/schema-equivalence.sh also compares column ACLs during the squash proof.
 */
export const PRIVILEGES: Record<string, string> = {
  absences: "SIUD",
  acks: "SIUD",
  availability: "SIUD",
  bookings: "SIU",
  cadenas: "SIU",
  canvases: "SIUD",
  catalogues: "SIU",
  categories: "SIU",
  contadores_instalacion: "SIU",
  convenio_config: "SIU",
  daily_close_chain: "SIU",
  daily_closes: "SI",
  department_hours: "SIUD",
  departments: "SIU",
  deployment: "S",
  device_profiles: "SIUD",
  device_zone_defaults: "SIUD",
  devices: "SIU",
  dining_tables: "SIU",
  drawer_opens: "SI",
  employments: "SIU",
  envio_flujo: "SIU",
  envios: "SIU",
  floor_zones: "SIU",
  google_oidc_states: "SIUD",
  incidents: "SI",
  ingredients: "SIU",
  invoice_series: "SI",
  join_requests: "SID",
  kitchen_courses: "SIU",
  kitchen_stations: "SIU",
  location_catalogues: "SID",
  locations: "SIU",
  management_account_actions: "SIU",
  management_sessions: "SIU",
  menu_item_option_groups: "SIUD",
  menu_item_options: "SIUD",
  menu_items: "SIU",
  menu_sections: "SIU",
  mirror_config: "S",
  node_membership: "SIU",
  nodes: "S",
  option_group_items: "SIUD",
  option_groups: "SIUD",
  order_amendments: "SI",
  order_service_contexts: "SIUD",
  payment_policy: "SIU",
  payment_refunds: "SIU",
  payments: "SIU",
  persons: "SIU",
  print_agents: "SIU",
  print_jobs: "SIU",
  printers: "SIU",
  preparation_routes: "SIUD",
  product_option_groups: "SIUD",
  products: "SIU",
  purchase_invoice_vat: "SIUD",
  purchase_invoices: "SIUD",
  recipe_lines: "SIUD",
  recovery_codes: "SIUD",
  registro_sif: "SIU",
  registros_facturacion: "SI",
  roster_versions: "SIUD",
  sale_lines: "SI",
  sale_settlements: "SI",
  sale_substitutions: "SI",
  sale_voids: "SI",
  sales: "SI",
  scheduled_runs: "SIU",
  sessions: "SIU",
  shift_swaps: "SIUD",
  shift_templates: "SIUD",
  shifts: "SIUD",
  station_printers: "SID",
  table_service_statuses: "SIU",
  tenant_credentials: "SIUD",
  tenant_receipts: "SIU",
  tenant_themes: "SIU",
  tenants: "S",
  tenders: "SI",
  ticket_items: "SIU",
  tills: "SIU",
  time_entries: "SI",
  totp_enrollments: "SIUD",
  webauthn_challenges: "SIUD",
  webauthn_credentials: "SIUD",
  workforce_chains: "SIU",
  working_order_counters: "SIU",
  working_order_lines: "SIUD",
  working_orders: "SIUD",
  working_line_contexts: "SIUD",
  zone_menus: "SIUD",
  zone_service_policies: "SIU",
};
