/**
 * What `app_user` was granted on each table, BEFORE the storage switch. Letters: S=SELECT I=INSERT
 * U=UPDATE D=DELETE T=TRUNCATE. The design it was taken from is
 * docs/superpowers/specs/2026-09-05-drop-rls-squash-and-outbox-deletion-design.md §1.
 *
 * THIS IS A FROZEN RECORD, NOT A MEASUREMENT, and it is unverified data: the engine it describes is
 * gone, so there are no roles and no grants to read it back from. The suite that used to do that,
 * `privileges.test.ts`, went with them, and `scripts/schema-equivalence.sh` cannot run over SQLite
 * migration sets. Nothing checks these letters against anything. Do not read a letter here as a
 * statement about what the running system refuses today — it refuses nothing.
 *
 * Its one live consumer is `scripts/write-path-tables.test.ts`, which takes the four tables marked
 * `S` — read and never written — and cross-checks them against its own frozen
 * `write-path-tables.json` while both files exist. That guard, not this matrix, is the whole of the
 * enforcement now, and its header states what it gives up.
 *
 * Its own blind spot, which outlived it: `has_table_privilege` measured TABLE grants only, so a
 * column-scoped grant — `UPDATE(next_number)` on `invoice_series` was the one that mattered — never
 * produced a letter here.
 */
export const PRIVILEGES: Record<string, string> = {
  absences: "SIUD",
  acks: "SIUD",
  availability: "SIUD",
  bookings: "SIU",
  cadenas: "SIU",
  canvases: "SIUD",
  card_readers: "SIU",
  catalogues: "SIU",
  categories: "SIUD",
  category_details: "SIUD",
  change_log: "SID",
  content_languages: "SIU",
  contadores_instalacion: "SIU",
  convenio_config: "SIU",
  daily_close_chain: "SIU",
  daily_closes: "SI",
  department_hours: "SIUD",
  departments: "SIU",
  deployment: "S",
  device_card_readers: "SIUD",
  device_profiles: "SIUD",
  device_zone_defaults: "SIUD",
  devices: "SIU",
  dining_tables: "SIU",
  drawer_opens: "SI",
  employments: "SIU",
  envio_flujo: "SIU",
  envios: "SIU",
  extra_list_items: "SIUD",
  extra_lists: "SIUD",
  floor_zones: "SIU",
  google_oidc_states: "SIUD",
  incidents: "SI",
  ingredients: "SIU",
  invoice_series: "SI",
  join_requests: "SID",
  kitchen_courses: "SIU",
  kitchen_stations: "SIU",
  location_catalogues: "SID",
  locations: "SIU",
  management_account_actions: "SIU",
  management_sessions: "SIU",
  menu_item_extra_items: "SIUD",
  menu_item_extra_lists: "SIUD",
  menu_items: "SIU",
  menu_item_variants: "SIUD",
  menu_sections: "SIU",
  media_images: "SIUD",
  media_image_data: "SI",
  mirror_config: "S",
  node_membership: "SIU",
  nodes: "S",
  option_labels: "SIUD",
  option_lists: "SIUD",
  order_amendments: "SI",
  order_service_contexts: "SIUD",
  payment_policy: "SIU",
  payment_refunds: "SIU",
  payments: "SIU",
  persons: "SIU",
  print_agents: "SIU",
  print_jobs: "SIU",
  printers: "SIU",
  preparation_routes: "SIUD",
  product_categories: "SIUD",
  product_modifiers: "SIUD",
  product_units: "SIUD",
  products: "SIU",
  product_variants: "SIUD",
  purchase_invoice_vat: "SIUD",
  purchase_invoices: "SIUD",
  recipe_lines: "SIUD",
  recovery_codes: "SIUD",
  registro_sif: "SIU",
  registros_facturacion: "SI",
  roster_versions: "SIUD",
  sale_lines: "SI",
  sale_settlements: "SI",
  sale_substitutions: "SI",
  sale_voids: "SI",
  sales: "SI",
  scheduled_runs: "SIU",
  sessions: "SIU",
  shift_swaps: "SIUD",
  shift_templates: "SIUD",
  shifts: "SIUD",
  station_printers: "SID",
  table_service_statuses: "SIU",
  tenant_credentials: "SIUD",
  tenant_receipts: "SIU",
  tenant_themes: "SIU",
  tenants: "S",
  tenders: "SI",
  ticket_items: "SIU",
  tills: "SIU",
  time_entries: "SI",
  totp_enrollments: "SIUD",
  unit_seed_states: "SIUD",
  units: "SIUD",
  webauthn_challenges: "SIUD",
  webauthn_credentials: "SIUD",
  workforce_chains: "SIU",
  working_order_counters: "SIU",
  working_order_lines: "SIUD",
  working_orders: "SIUD",
  working_line_contexts: "SIUD",
  zone_menus: "SIUD",
  zone_service_policies: "SIU",
};
