-- Hand-written custom migration (drizzle-kit models no roles/grants; sync_cursor is a raw-SQL
-- table, so drizzle-kit has nothing to diff and 0003_snapshot.json is a copy of 0002's) — the
-- 0000/0001/0002 idiom (0002_sync_cursor_lane.sql:1-6). Runs LAST in migrations.manifest.json's
-- `sync` set, after 0000/0001/0002, so sync_cursor and the sync_retention role already exist.
--
-- WHAT THIS BUILDS. The one grant the dead-subscriber eviction verb needs. 0001 gave sync_retention
-- SELECT, INSERT, UPDATE on sync_cursor (0001_sync_retention.sql:55) but NOT DELETE; evictSubscriber
-- (packages/sync/src/retention.ts) releases a genuinely-dead subscriber by DELETEing its cursor rows
-- so pruneSyncLog's per-origin min advances past it (spec §3.3). sync_cursor carries no tenant_id and
-- no RLS (0000_sync_outbox.sql:95-99), so a plain object GRANT is the whole mechanism — no policy.
-- Only sync_retention gets DELETE; sync_tailer/app_user are NOT widened (CLAUDE.md §3).
GRANT DELETE ON sync_cursor TO sync_retention;
