-- The generic-layer link for rectificativas (corrective invoices), piece 2 of the fiscal
-- sequence. docs/superpowers/plans/2026-08-02-rectificativas.md §2.1.
--
-- `corrects_sale_id` is the projection of "this sale corrects that one": set on a rectificativa,
-- NULL on an ordinary sale. The composite (tenant_id, corrects_sale_id) FK back onto sales
-- mirrors sale_lines_sale_fk/tenders_sale_fk so a corrective may only point at a sale of its own
-- tenant; under MATCH SIMPLE a NULL corrects_sale_id satisfies the FK, leaving ordinary sales
-- untouched. NOT unique — a sale may be corrected more than once (successive rectificativas),
-- unlike sale_voids' one-void-per-sale — so it takes a plain index, not a unique one.
--
-- sales_total_ck relaxes from `total >= 0` to `total >= 0 OR corrects_sale_id IS NOT NULL`: a
-- rectificativa por diferencias carries a NEGATIVE total (docs/compliance/verifactu-findings.md
-- §10.2), and record-sale passes `total` verbatim into the fiscal record's ImporteTotal, which
-- the huella hashes — so this column must be allowed to hold that negative value. An ordinary
-- sale (link NULL) is still rejected when negative.
--
-- NULLABLE with no backfill, deliberately: no production deployment exists (CLAUDE.md §3), so
-- there is no data to migrate. Immutability and RLS carry automatically — sales already REVOKEs
-- UPDATE/DELETE from app_user and forces RLS, and both are table-wide, covering the new column
-- with no privilege/trigger/policy DDL here (the same reasoning 0009_registro_entorno relied on).
--
-- Generated by plain `drizzle-kit generate` (not --custom) against ./src/schema/sales.ts, so
-- drizzle/meta/0013_snapshot.json stays an accurate record of this table's shape; a --custom
-- migration on an already-tracked table would leave the snapshot missing this column and the next
-- plain `generate` would re-propose it.
ALTER TABLE "sales" DROP CONSTRAINT "sales_total_ck";--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "corrects_sale_id" uuid;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_corrects_fk" FOREIGN KEY ("tenant_id","corrects_sale_id") REFERENCES "public"."sales"("tenant_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "sales_corrects_idx" ON "sales" USING btree ("tenant_id","corrects_sale_id");--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_total_ck" CHECK ("sales"."total" >= 0 or "sales"."corrects_sale_id" is not null);