-- Park & retrieve schema (Counter POS sub-project 7b, Task 1): the columns that persist a counter
-- till's working order across registers, the sale-idempotency key, and the per-node order-number
-- counter table.
--
-- Generated by `drizzle-kit generate --name park_retrieve`, then HAND-EDITED in two ways
-- (mirroring 0004_working_orders.sql, which did the same):
--
--   1. Statements REORDERED. drizzle-kit emitted `working_order_lines_product_fk` BEFORE
--      `products_tenant_id_key`, but that FK references products(tenant_id, id) and Postgres
--      refuses a foreign key whose referenced columns carry no matching unique constraint yet —
--      the migration would die "there is no unique constraint matching given keys for referenced
--      table \"products\"". Every ADD CONSTRAINT ... FOREIGN KEY here is therefore placed after
--      the UNIQUE it targets. The snapshot (meta/0029_snapshot.json) is derived from the TS schema,
--      not from this file's statement order, so reordering here does not desynchronise it — proven
--      by re-running `drizzle-kit generate`, which reports "No schema changes".
--
--   2. FORCE ROW LEVEL SECURITY + the tenant-isolation policy + the app_user grant appended for
--      working_order_counters. `.enableRLS()` emits only ENABLE (below); Drizzle emits neither
--      FORCE, CREATE POLICY nor GRANT. These mirror 0027_light_smiling_tiger.sql (catalogue tables)
--      and 0004_working_orders.sql:44-98 verbatim. `current_tenant_id()` and `app_user` already
--      exist from 0001 and are not recreated.

--> The composite UNIQUE that working_order_lines_product_fk targets. First, so the FK below finds it.
ALTER TABLE "products" ADD CONSTRAINT "products_tenant_id_key" UNIQUE("tenant_id","id");--> statement-breakpoint

ALTER TABLE "working_orders" ADD COLUMN "order_number" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "working_orders" ADD COLUMN "label" text;--> statement-breakpoint

ALTER TABLE "working_order_lines" ADD COLUMN "product_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "working_order_lines" ADD CONSTRAINT "working_order_lines_product_fk" FOREIGN KEY ("tenant_id","product_id") REFERENCES "public"."products"("tenant_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint

ALTER TABLE "sales" ADD COLUMN "working_order_id" uuid;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_working_order_fk" FOREIGN KEY ("tenant_id","working_order_id") REFERENCES "public"."working_orders"("tenant_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_working_order_id_key" UNIQUE("tenant_id","working_order_id");--> statement-breakpoint

CREATE TABLE "working_order_counters" (
	"tenant_id" uuid NOT NULL,
	"node_id" uuid NOT NULL,
	"next_number" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "working_order_counters_pk" PRIMARY KEY("tenant_id","node_id")
);
--> statement-breakpoint
ALTER TABLE "working_order_counters" ADD CONSTRAINT "working_order_counters_node_fk" FOREIGN KEY ("tenant_id","node_id") REFERENCES "public"."nodes"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "working_order_counters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

-- Tenant isolation for the new counter table (hand-written — see header). FORCE so the migration
-- owner is subject to the policy too (without it the owner bypasses RLS, and migrations run as
-- owner); a FOR ALL policy whose USING filters reads and WITH CHECK filters writes, using
-- current_tenant_id() (fails closed on a malformed app.tenant_id, unlike a bare current_setting
-- cast). MUTABLE, so no immutability triggers: a counter is incremented on every allocation.
ALTER TABLE "working_order_counters" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "working_order_counters_tenant_isolation" ON "working_order_counters"
  FOR ALL
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());--> statement-breakpoint

-- SELECT, INSERT, UPDATE — the till reads and bumps its own counter — but NO DELETE: a counter is
-- never removed (a node keeps its order-number line for the life of the node). The same rule 0027
-- states for the catalogue tables and 0001 for locations/tills.
GRANT SELECT, INSERT, UPDATE ON "working_order_counters" TO app_user;
