-- Counter POS prepare & collect (sub-project 7c): the placed state + rewritten enforce_transition,
-- the locked gross unit price, the per-location order_flow, the append-only order_amendments log,
-- and the mutable order_prep queue.
--
-- Generated by `drizzle-kit generate --name prepare_collect`, then HAND-EDITED in two ways
-- (mirroring 0029_park_retrieve.sql / 0004_working_orders.sql, which did the same):
--
--   1. Statements REORDERED. drizzle-kit emitted `tills_tenant_id_key` (the UNIQUE the new
--      order_amendments_till_fk targets) LAST, after that FK — but Postgres refuses a foreign key
--      whose referenced columns carry no matching unique constraint yet ("there is no unique
--      constraint matching given keys for referenced table \"tills\""). Every ADD CONSTRAINT ...
--      FOREIGN KEY here is therefore placed after the UNIQUE it targets. The snapshot
--      (meta/0030_snapshot.json) is derived from the TS schema, not from this file's statement
--      order, so reordering here does not desynchronise it — proven by re-running
--      `drizzle-kit generate`, which reports "No schema changes".
--
--   2. FORCE ROW LEVEL SECURITY + the tenant-isolation policies + the app_user grants + the
--      immutability/TRUNCATE triggers on order_amendments + the enforce_transition rewrite appended
--      by hand. `.enableRLS()` emits only ENABLE (below); Drizzle emits none of the rest. These
--      mirror 0005_sales.sql (append-only immutability) and 0029_park_retrieve.sql (mutable
--      working_order_counters) verbatim. `current_tenant_id()`, `reject_mutation()` and `app_user`
--      already exist from 0001/0002 and are not recreated.

-- The new non-terminal state, positioned between 'open' and 'settled' to match the TS enum's
-- declared order (open, placed, settled, abandoned) — `BEFORE 'settled'` is what `drizzle-kit
-- generate` emits from that declaration, and the snapshot records the same order. `ADD VALUE` is
-- late-bound: the enforce_transition body below compares against 'placed' as a string literal
-- resolved at RUNTIME (a plpgsql function body is parsed on first execution, not at CREATE), never
-- at CREATE FUNCTION, so this does not trip 55P04 in the same migration — and nothing here UPDATEs a
-- working_orders row, so the trigger never fires during this transaction (the workforce_entry_kind
-- 'correction' precedent, 0002_workforce_corrections.sql).
ALTER TYPE "public"."working_order_status" ADD VALUE 'placed' BEFORE 'settled';--> statement-breakpoint

CREATE TYPE "public"."order_flow" AS ENUM('prepay', 'invoice_first', 'ticket_then_pay');--> statement-breakpoint
CREATE TYPE "public"."order_amendment_kind" AS ENUM('order_placed', 'order_cancelled');--> statement-breakpoint
CREATE TYPE "public"."prep_state" AS ENUM('queued', 'preparing', 'ready', 'collected');--> statement-breakpoint

ALTER TABLE "working_order_lines" ADD COLUMN "unit_price_gross" numeric(12, 2) NOT NULL;--> statement-breakpoint
ALTER TABLE "locations" ADD COLUMN "order_flow" "order_flow" DEFAULT 'prepay' NOT NULL;--> statement-breakpoint

-- The composite UNIQUE order_amendments_till_fk targets. First, so the FK finds it (0029 reorder).
ALTER TABLE "tills" ADD CONSTRAINT "tills_tenant_id_key" UNIQUE("tenant_id","id");--> statement-breakpoint

-- order_amendments (append-only, immutable).
CREATE TABLE "order_amendments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"working_order_id" uuid NOT NULL,
	"sequence_no" integer NOT NULL,
	"kind" "order_amendment_kind" NOT NULL,
	"actor_id" uuid NOT NULL,
	"reason" text,
	"captured_by_till_id" uuid NOT NULL,
	"captured_by_node_id" uuid NOT NULL,
	"event_at" timestamp with time zone NOT NULL,
	"event_offset_minutes" integer NOT NULL,
	"entry_hash" text NOT NULL,
	"prev_entry_hash" text,
	"is_first_entry" boolean NOT NULL,
	CONSTRAINT "order_amendments_chain_position_key" UNIQUE("tenant_id","working_order_id","sequence_no"),
	CONSTRAINT "order_amendments_sequence_no_ck" CHECK ("order_amendments"."sequence_no" > 0),
	CONSTRAINT "order_amendments_entry_hash_ck" CHECK ("order_amendments"."entry_hash" ~ '^[0-9A-F]{64}$'),
	CONSTRAINT "order_amendments_event_offset_ck" CHECK ("order_amendments"."event_offset_minutes" between -840 and 840),
	CONSTRAINT "order_amendments_event_at_second_ck" CHECK (date_trunc('second', "order_amendments"."event_at") = "order_amendments"."event_at"),
	CONSTRAINT "order_amendments_chaining_ck" CHECK (("order_amendments"."is_first_entry" and "order_amendments"."prev_entry_hash" is null)
          or (not "order_amendments"."is_first_entry" and "order_amendments"."prev_entry_hash" is not null))
);
--> statement-breakpoint
ALTER TABLE "order_amendments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "order_amendments" ADD CONSTRAINT "order_amendments_order_fk" FOREIGN KEY ("tenant_id","working_order_id") REFERENCES "public"."working_orders"("tenant_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_amendments" ADD CONSTRAINT "order_amendments_till_fk" FOREIGN KEY ("tenant_id","captured_by_till_id") REFERENCES "public"."tills"("tenant_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_amendments" ADD CONSTRAINT "order_amendments_node_fk" FOREIGN KEY ("tenant_id","captured_by_node_id") REFERENCES "public"."nodes"("tenant_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "order_amendments_order_idx" ON "order_amendments" USING btree ("tenant_id","working_order_id");--> statement-breakpoint

-- order_prep (mutable — the 0029 working_order_counters shape).
CREATE TABLE "order_prep" (
	"tenant_id" uuid NOT NULL,
	"working_order_id" uuid NOT NULL,
	"node_id" uuid NOT NULL,
	"state" "prep_state" DEFAULT 'queued' NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"preparing_at" timestamp with time zone,
	"ready_at" timestamp with time zone,
	"collected_at" timestamp with time zone,
	CONSTRAINT "order_prep_pk" PRIMARY KEY("tenant_id","working_order_id")
);
--> statement-breakpoint
ALTER TABLE "order_prep" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "order_prep" ADD CONSTRAINT "order_prep_order_fk" FOREIGN KEY ("tenant_id","working_order_id") REFERENCES "public"."working_orders"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_prep" ADD CONSTRAINT "order_prep_node_fk" FOREIGN KEY ("tenant_id","node_id") REFERENCES "public"."nodes"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "order_prep_queue_idx" ON "order_prep" USING btree ("tenant_id","node_id","state");--> statement-breakpoint

-- Replace the enforce_transition function body with the extended state machine (design §5). The
-- OLD body rejected ANY update of a non-open row; the NEW body permits open → {open,placed,settled,
-- abandoned} (open → open preserves label edits on an open order — updateHeldOrder; open → settled
-- the walk-up; open → placed placing; open → abandoned discard) and placed → {settled,abandoned}
-- (collect / cancel), and rejects everything else — every transition OUT of settled/abandoned
-- (terminal, unchanged) and placed → {open,placed} (no un-place, and a non-status update of a
-- placed row is rejected, which IS the composition freeze at the row level). CLAUDE.md §1: this is
-- a rewrite, and the comment is rewritten with it.
CREATE OR REPLACE FUNCTION working_orders_enforce_transition()
  RETURNS trigger
  LANGUAGE plpgsql
  SET search_path = pg_catalog, public
AS $$
BEGIN
  IF OLD.status = 'open' THEN
    -- An open order may change freely (a label edit keeps status open) or move to any next state.
    RETURN NEW;
  ELSIF OLD.status = 'placed' AND NEW.status IN ('settled', 'abandoned') THEN
    -- A placed order may only be settled (collect) or abandoned (cancel).
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'working order % cannot transition from % to %', OLD.id, OLD.status, NEW.status;
END;
$$;
--> statement-breakpoint

-- order_amendments tenant isolation + immutability (0002/0005 idiom): FORCE, FOR ALL policy on
-- current_tenant_id(), REVOKE ALL then GRANT SELECT, INSERT (append-only — no UPDATE/DELETE), plus
-- reject_mutation on UPDATE/DELETE and a BEFORE TRUNCATE statement trigger.
ALTER TABLE "order_amendments" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "order_amendments_tenant_isolation" ON "order_amendments"
  FOR ALL USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());--> statement-breakpoint
REVOKE ALL ON "order_amendments" FROM app_user;--> statement-breakpoint
GRANT SELECT, INSERT ON "order_amendments" TO app_user;--> statement-breakpoint
CREATE TRIGGER "order_amendments_enforce_immutability"
  BEFORE UPDATE OR DELETE ON "order_amendments"
  FOR EACH ROW EXECUTE FUNCTION reject_mutation();--> statement-breakpoint
CREATE TRIGGER "order_amendments_block_truncate"
  BEFORE TRUNCATE ON "order_amendments"
  FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();--> statement-breakpoint

-- order_prep tenant isolation (0029 idiom): FORCE + FOR ALL policy + GRANT SELECT, INSERT, UPDATE
-- (mutable — prep advances) but NO DELETE (a prep record is never removed; a cancelled order's is
-- cascaded by the order FK). MUTABLE, so no immutability triggers.
ALTER TABLE "order_prep" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "order_prep_tenant_isolation" ON "order_prep"
  FOR ALL USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE ON "order_prep" TO app_user;
