export const CATALOGUE_CONFIGURATION_TRANSFER = {
  kind: "tables",
  tables: [
    { name: "category_details" },
    { name: "labels" },
    { name: "product_labels" },
    { name: "content_languages" },
    { name: "unit_seed_states" },
    { name: "units" },
    { name: "product_units" },
    { name: "menu_sections" },
    { name: "menu_items" },
    { name: "menu_item_variant_overrides" },
    { name: "option_lists" },
    { name: "option_labels" },
    { name: "extra_lists" },
    { name: "extra_list_items" },
    { name: "menu_item_extra_lists" },
    { name: "menu_item_extra_items" },
    { name: "product_modifiers" },
    { name: "sections" },
    { name: "section_members" },
  ],
} as const;
