import type { ReceiptLabels } from "@waitron/country";

/**
 * The fixed words of a printed receipt, per official language. The words printed around the
 * receipt's QR are not here: the fiscal backend supplies them (`FiscalBackend.receiptQrText`).
 */
export const SPAIN_RECEIPT_LABELS = {
  "es-ES": {
    nif: "NIF",
    invoice: "Factura",
    date: "Fecha",
    order: "Pedido",
    base: "Base",
    vat: "IVA",
    total: "TOTAL",
    cash: "Efectivo",
    change: "Cambio",
    card: "Tarjeta",
    tip: "Propina",
    charged: "Cobrado",
    refund: "Devolución",
    comp: "Invitación",
    discount: "Descuento",
    reference: "Ref.",
    duplicate: "DUPLICADO",
    practice: "PRUEBA - SIN COBRO REAL",
  },
  "ca-ES": {
    nif: "NIF",
    invoice: "Factura",
    date: "Data",
    order: "Comanda",
    base: "Base",
    vat: "IVA",
    total: "TOTAL",
    cash: "Efectiu",
    change: "Canvi",
    card: "Targeta",
    tip: "Propina",
    charged: "Cobrat",
    refund: "Devolució",
    comp: "Invitació",
    discount: "Descompte",
    reference: "Ref.",
    duplicate: "DUPLICAT",
    practice: "PROVA - SENSE COBRAMENT REAL",
  },
  "gl-ES": {
    nif: "NIF",
    invoice: "Factura",
    date: "Data",
    order: "Pedido",
    base: "Base",
    vat: "IVE",
    total: "TOTAL",
    cash: "Efectivo",
    change: "Cambio",
    card: "Tarxeta",
    tip: "Propina",
    charged: "Cobrado",
    refund: "Devolución",
    comp: "Invitación",
    discount: "Desconto",
    reference: "Ref.",
    duplicate: "DUPLICADO",
    practice: "PROBA - SEN COBRO REAL",
  },
  "eu-ES": {
    nif: "IFZ",
    invoice: "Faktura",
    date: "Data",
    order: "Eskaera",
    base: "Oinarria",
    vat: "BEZ",
    total: "GUZTIRA",
    cash: "Eskudirua",
    change: "Itzulia",
    card: "Txartela",
    tip: "Eskupekoa",
    charged: "Kobratua",
    refund: "Itzulketa",
    comp: "Gonbidapena",
    discount: "Deskontua",
    reference: "Erref.",
    duplicate: "BIKOIZKARIA",
    practice: "PROBA - BENETAKO KOBRANTZARIK GABE",
  },
} as const satisfies Readonly<Record<string, ReceiptLabels>>;
