// The public surface of @waitron/provisioning. Re-exports only — no logic here.
export { runCli } from "./cli.js";
export type { CliDeps } from "./cli.js";
export { assertIdentifier, generatePassword, quoteIdent } from "./identifiers.js";
export { generateKeyRing, runKeyring } from "./keyring-command.js";
export type { GeneratedKeyRing } from "./keyring-command.js";
export type { ProvisioningIo } from "./io.js";
export { INSTANCE_ROLES, readInstanceState } from "./instance-state.js";
export type { InstanceRole, InstanceState, InsideState, RoleFacts } from "./instance-state.js";
export { planInstance } from "./instance-plan.js";
export type { InstanceAction, InstanceRequest } from "./instance-plan.js";
export { applyInstance, withDatabase } from "./instance-apply.js";
export type { ApplyDeps } from "./instance-apply.js";
export { formatStatus } from "./status-command.js";
export { planVenue, describeVenueAction } from "./venue-plan.js";
export type { VenueRequest, VenueAction } from "./venue-plan.js";
export { applyVenue } from "./venue-apply.js";
export type { VenueApplyDeps, VenueResult } from "./venue-apply.js";
export { adoptVenue } from "./venue-adopt.js";
export type { AdoptResult, AdoptVenueDeps, AdoptVenueRows, VenueRow } from "./venue-adopt.js";
export { FISCAL_TERRITORIES, resolveFiscalModules } from "./fiscal-modules.js";
export type { FiscalModules } from "./fiscal-modules.js";
export { obligadoTenantId } from "./tenant-id.js";
import "./errors.js";
