import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { ALL_MODULES } from "../packages/composition/src/index.js";
import { packageDirOf } from "../packages/module/src/module.js";

/**
 * Every module descriptor's `requires` must NAME every cross-module dependency its migrations
 * create in SQL. A module depends on another when its `drizzle/*.sql` either FK-`REFERENCES` a
 * table the other module owns or installs a `CREATE TRIGGER … ON <table>` against one — both edges
 * force a migration-order dependency, because the referenced or triggered table must exist first.
 *
 * WHY THIS HAS TO BE A TREE-WIDE ROOT-PROJECT PROGRAM. The `requires` graph lives in one package
 * (`@waitron/composition`) but the evidence for it — the `CREATE TABLE`/`REFERENCES`/`CREATE
 * TRIGGER` statements — is spread across every domain package's `drizzle/` directory. No
 * per-package suite can see both: a package that under-declares `requires` has, by construction,
 * the SQL in one package and the descriptor in another, and each package's own `test:coverage`
 * loads only its own tree. Only a program that reads the composition list's descriptors AND every
 * `packages/<pkg>/drizzle` at once can cross-check them. That is why it sits in the root Vitest
 * project beside `errors-reachable.test.ts` and `guarded-teardowns.test.ts` (see the repo-root
 * `vitest.config.ts`), not in any package.
 *
 * WHY THE TRIGGER EDGE IS CHECKED AT ALL. SP-1c derived the first `requires` graph from FK
 * `REFERENCES` alone and missed two edges a package created by installing capture triggers on
 * another module's tables, with no FK between them. Review caught them by hand; CLAUDE.md §3
 * carries the rule.
 *
 * MECHANISM. This reads SQL as TEXT (never executing it). It maps every `CREATE TABLE <name>` to
 * its owning module, then for each module scans for the edge kinds (FK reference, trigger),
 * resolves each target table to its owner, drops same-module targets, and asserts the surviving
 * cross-module set is a subset of the descriptor's declared `requires`. A package is in scope only
 * if a descriptor's `migrations.from` (`../<pkg>/drizzle`) points at it, and the module NAME is
 * read off that descriptor rather than assumed equal to the package DIR name.
 *
 * DIALECT. The tree's migrations are generated by `drizzle-kit`'s SQLite dialect, which quotes
 * identifiers with backticks and writes an FK inline as ``REFERENCES `t`(`id`)`` — no space, no
 * schema qualifier. Every regex below therefore accepts a backtick, a double quote or nothing, and
 * keeps the double-quoted and optionally `public.`-qualified spellings too; each spelling has a
 * control test, because a spelling the detector misses makes every edge written that way invisible.
 *
 * KNOWN LIMITATIONS, stated rather than papered over (CLAUDE.md §1):
 * - `[BRACKET]` QUOTING IS NOT HANDLED, and SQLite accepts it. sqlite3 3.51 created
 *   `CREATE TABLE [gadgets]([id] text)` and registered `REFERENCES [gadgets]([id])` against it. A
 *   hand-written migration spelling an identifier that way would have its table read as owned by
 *   nobody and its FK edge dropped — silently, because a dropped edge looks exactly like an honest
 *   descriptor. `drizzle-kit`'s generated SQL uses backticks, so nothing in the tree does this
 *   today; a migration that starts to is outside this guard.
 * - THE TRIGGER DETECTOR HAS A TREE ANCHOR AGAIN, and this entry said it did not until 2026-09-22.
 *   The claim was taken on 2026-09-21, when the SQLite regeneration had just replaced every
 *   hand-written custom migration with a generated baseline; two hand-written sets have landed since.
 *   `grep -Ein 'create (constraint )?trigger'` over every `packages/<pkg>/drizzle/*.sql` now matches
 *   `packages/db/drizzle/0001_behavioural_triggers.sql` and
 *   `packages/media/drizzle/0001_image_references.sql`, and media's triggers sit ON tables core and
 *   catalogue create — real cross-set edges, which is why this guard passes only because media
 *   DECLARES both in its `requires`. What the scan still cannot see is append-only enforcement,
 *   which is runtime code (`packages/store/src/append-only.ts`). The `CREATE CONSTRAINT TRIGGER`
 *   spelling it also accepts is
 *   PostgreSQL-only: sqlite3 3.51 answers `near "CONSTRAINT": syntax error`, so those two controls
 *   pin a spelling this engine cannot run.
 * - A SQLITE TRIGGER'S BODY IS NOT READ. On PostgreSQL a trigger reached another module through
 *   `EXECUTE FUNCTION <fn>`, and that edge kind was detected here; SQLite has no functions at all
 *   (sqlite3 3.51: `CREATE FUNCTION` → `near "FUNCTION": syntax error`, and `FOR EACH ROW EXECUTE
 *   FUNCTION f()` → `near "EXECUTE": syntax error`), so the detector was deleted as dead syntax. A
 *   SQLite trigger instead carries statements between `BEGIN` and `END`, and an `INSERT INTO
 *   <other module's table>` in there is a real cross-module edge that NEITHER remaining detector
 *   sees. Nothing covers that today.
 * - It is a regex over comment- and string-stripped text, NOT a SQL parser. `stripSql` blanks
 *   slash-star blocks, `--` line comments, and `'…'` string literals (preserving line numbers),
 *   so a `references`/`create trigger` mention in any of those is ignored — pinned by the
 *   detector's negative controls below. But a trigger whose `ON <table>` is separated from the
 *   trigger name by content the `.*?` cannot span cleanly, or a table named with quoting the
 *   ``["`]?(?:public["`]?\.)?["`]?(\w+)["`]?`` shape does not cover, could be missed. The defence
 *   against that is not a proof of totality — it is the vacuous-pass anchor, which asserts the
 *   scan actually FOUND a known real edge (`workforce→identity` by FK reference on `persons`) in
 *   the tree's ACTUAL spelling. If the tree's SQL dialect drifts out from under the FK regex, that
 *   anchor goes red rather than the guard passing empty (CLAUDE.md §1, "a measurement where both
 *   answers look alike measures nothing").
 * - The stripping is single-pass and naive: `--` is treated as a comment start even inside a
 *   string literal (line comments are blanked before strings), and a `'` inside a `--` comment
 *   cannot open a string (comments are blanked first). The real tree is clean under this order —
 *   verified by the anchor and the empty tree-wide result — but a future migration mixing the two
 *   on one line could confuse it. A full tokenizer was not built; the failure mode is a stale
 *   anchor, not a silent pass.
 * - Like every file under `scripts/`, this is NOT typechecked — `pnpm typecheck` is `pnpm -r
 *   typecheck` and never visits the workspace root (CLAUDE.md §2/§4). So it is kept plain and its
 *   one cross-package import (`ALL_MODULES`) is used only for runtime values, never for a shape
 *   only a typechecker would validate.
 */

const REPO_ROOT = join(import.meta.dirname, "..");
const PACKAGES_DIR = join(REPO_ROOT, "packages");

/** ``CREATE TABLE [`|"]<name>[`|"]`` — backtick-quoted (drizzle-kit's SQLite spelling),
 * double-quoted, or bare, optionally schema-qualified and IF NOT EXISTS. */
const CREATE_TABLE =
  /\bcreate\s+table\s+(?:if\s+not\s+exists\s+)?["`]?(?:public["`]?\.)?["`]?(\w+)["`]?/gi;
/** ``REFERENCES [`|"]<table>[`|"]`` — the FK edge. The tree writes ``REFERENCES `persons`(`id`)``
 * with no space before the column list; `"public"."t"` and bare `t` are accepted too. */
const REFERENCES = /\breferences\s+["`]?(?:public["`]?\.)?["`]?(\w+)["`]?/gi;
/** ``CREATE [CONSTRAINT] TRIGGER <name> … ON [`|"]<table>[`|"]`` — the trigger edge. The
 * `s` (dotAll) flag lets `.*?` span a multi-line trigger (name on line 1, `ON` clause on a later
 * line); `\bon\b` first-matches the real ON clause because no keyword between it and the trigger
 * name (`AFTER`/`INSERT`/`UPDATE`/`DELETE`/`OR`/`OF`/`BEFORE`/`TRUNCATE`/`CONSTRAINT`/
 * `DEFERRABLE`) is the word "on". The `CONSTRAINT` form is PostgreSQL-only — see the header's
 * known limitations. */
const CREATE_TRIGGER =
  /\bcreate\s+(?:constraint\s+)?trigger\s+\S+\s+.*?\bon\s+["`]?(?:public["`]?\.)?["`]?(\w+)["`]?/gis;

const EDGE_KINDS = [
  ["FK reference", REFERENCES],
  ["trigger", CREATE_TRIGGER],
] as const;

/** Blank block comments, `--` line comments, and `'…'` string literals to whitespace, preserving
 * line count. Naive by design — see the header's known-limitations block. */
function stripSql(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, (block) => block.replace(/[^\n]/g, " "))
    .split("\n")
    .map((line) => line.replace(/--.*$/, ""))
    .join("\n")
    .replace(/'(?:[^']|'')*'/g, (literal) => literal.replace(/[^\n]/g, " "));
}

/** From every descriptor's `migrations.from` (`../<pkg>/drizzle`), the package DIR → module NAME
 * map, through `@waitron/module`'s `packageDirOf` — the one place that parses that string to
 * recover the package directory. A package is only in scope if some descriptor points at it, and
 * the name comes off the descriptor, so a module whose name and directory differ resolves to the
 * name it declares rather than to its directory. A descriptor whose `from` has another shape
 * throws rather than silently dropping its package from the scan. */
function packageDirToModule(): Map<string, string> {
  return new Map(ALL_MODULES.map((module) => [packageDirOf(module), module.name]));
}

interface DrizzlePackage {
  moduleName: string;
  packageDir: string;
  /** Raw SQL of each `drizzle/*.sql` file; stripping happens at scan time. */
  sqls: string[];
}

function discoverDrizzlePackages(): DrizzlePackage[] {
  const discovered: DrizzlePackage[] = [];
  for (const [packageDir, moduleName] of packageDirToModule()) {
    const drizzleDir = join(PACKAGES_DIR, packageDir, "drizzle");
    let entries: string[];
    try {
      entries = readdirSync(drizzleDir);
    } catch {
      // A descriptor pointing at a package with no `drizzle/` dir: skip it rather than crash. The
      // vacuous-pass anchor's floor catches a discovery that silently found too few packages.
      continue;
    }
    const sqls = entries
      .filter((name) => name.endsWith(".sql"))
      .map((name) => readFileSync(join(drizzleDir, name), "utf8"));
    discovered.push({ moduleName, packageDir, sqls });
  }
  return discovered;
}

/** Every `CREATE TABLE <name>` across the in-scope packages, mapped to its owning module. */
function ownerOfTable(discovered: DrizzlePackage[]): Map<string, string> {
  const owner = new Map<string, string>();
  for (const { moduleName, sqls } of discovered) {
    for (const raw of sqls) {
      for (const match of stripSql(raw).matchAll(CREATE_TABLE)) {
        const table = match[1]?.toLowerCase();
        if (table !== undefined) owner.set(table, moduleName);
      }
    }
  }
  return owner;
}

interface Edge {
  dep: string;
  kind: string;
  /** The depended-upon table. */
  target: string;
}

/** The cross-module edges a single SQL file's DDL creates for `moduleName`: every FK reference and
 * trigger whose target table is owned by a DIFFERENT in-scope module. Same-module targets and
 * targets owned by no in-scope package are dropped. */
function edgeDetails(rawSql: string, moduleName: string, owner: Map<string, string>): Edge[] {
  const sql = stripSql(rawSql);
  const edges: Edge[] = [];
  for (const [kind, pattern] of EDGE_KINDS) {
    for (const match of sql.matchAll(pattern)) {
      const target = match[1]?.toLowerCase();
      if (target === undefined) continue;
      const dep = owner.get(target);
      if (dep !== undefined && dep !== moduleName) edges.push({ dep, kind, target });
    }
  }
  return edges;
}

/** The set of module NAMES `moduleName` depends on, per this SQL — the `dep` field of its edges. */
function edgesFor(rawSql: string, moduleName: string, owner: Map<string, string>): Set<string> {
  return new Set(edgeDetails(rawSql, moduleName, owner).map((edge) => edge.dep));
}

/** The dependency names a descriptor DECLARES: `requires.core` (as "core") plus `requires.modules`. */
function declaredDepsOf(moduleName: string): Set<string> {
  const module = ALL_MODULES.find((candidate) => candidate.name === moduleName);
  const declared = new Set<string>();
  if (module?.requires?.core !== undefined) declared.add("core");
  for (const dep of Object.keys(module?.requires?.modules ?? {})) declared.add(dep);
  return declared;
}

describe("the detector itself", () => {
  // `alpha` owns `widgets`; `beta` owns `gadgets`. A `references`/`trigger` from an `alpha` file onto
  // `gadgets` is a cross-module edge; onto `widgets` it is not.
  const OWNER = new Map([
    ["widgets", "alpha"],
    ["gadgets", "beta"],
  ]);

  // The spelling the tree actually contains: backtick-quoted, inline in the CREATE TABLE, with no
  // space between the table name and its column list. This is the control for the backtick
  // tolerance — remove the backtick from the REFERENCES character class and this goes red, as does
  // the tree anchor below.
  it("flags a cross-module FK reference in the SQLite spelling", () => {
    const sql =
      "CREATE TABLE `widgets` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`g_id` text NOT NULL,\n\tFOREIGN KEY (`g_id`) REFERENCES `gadgets`(`id`) ON UPDATE no action ON DELETE restrict\n);";
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual(["beta"]);
  });

  // The table-ownership half of the same tolerance: a backtick-quoted CREATE TABLE must resolve its
  // owner, or every edge onto that table silently resolves to no owner and is dropped.
  it("resolves table ownership from a backtick-quoted CREATE TABLE", () => {
    const discovered: DrizzlePackage[] = [
      { moduleName: "alpha", packageDir: "alpha", sqls: ["CREATE TABLE `widgets` (`id` text);"] },
      { moduleName: "beta", packageDir: "beta", sqls: ['CREATE TABLE "gadgets" ("id" text);'] },
    ];
    expect(ownerOfTable(discovered)).toEqual(
      new Map([
        ["widgets", "alpha"],
        ["gadgets", "beta"],
      ]),
    );
  });

  // A trigger in the form SQLite accepts: backtick-quoted names, statements between BEGIN and END
  // instead of a function call. Verified against sqlite3 3.51 — it is accepted and the trigger
  // fires (`Error: stepping, append-only (19)` on the UPDATE).
  it("flags a cross-module trigger in the SQLite spelling", () => {
    const sql =
      "CREATE TRIGGER `gadgets_append_only` BEFORE UPDATE ON `gadgets`\nBEGIN\n  SELECT RAISE(ABORT, 'append-only');\nEND;";
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual(["beta"]);
  });

  it("flags a cross-module FK reference", () => {
    const sql = `alter table "widgets" add constraint w_g_fk foreign key ("g_id")\n  references "public"."gadgets"("id");`;
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual(["beta"]);
  });

  it("flags a cross-module capture trigger", () => {
    const sql = `create trigger gadgets_capture after insert or update on gadgets\n  for each row execute function capture();`;
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual(["beta"]);
  });

  // The CONSTRAINT-trigger form is a distinct spelling PostgreSQL accepts (including deferrable
  // checks). It is PostgreSQL-only — sqlite3 3.51 answers `near "CONSTRAINT": syntax error` — so
  // these two cases say nothing about the engine the tree now generates for. The tolerance is two
  // optional words inside a detector that is otherwise live, so it is left in place; the cases are
  // labelled rather than deleted so nobody later reads them as evidence about SQLite.
  it("flags a cross-module CREATE CONSTRAINT TRIGGER", () => {
    const sql = `create constraint trigger gadgets_check after insert on gadgets\n  deferrable initially deferred\n  for each row execute function gadgets_check();`;
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual(["beta"]);
  });

  it("accepts the CREATE CONSTRAINT TRIGGER spelling", () => {
    const sql = `CREATE CONSTRAINT TRIGGER sales_check_tender_coverage\n  AFTER INSERT ON sales\n  DEFERRABLE INITIALLY DEFERRED\n  FOR EACH ROW EXECUTE FUNCTION sales_check_tender_coverage();`;
    const owner = new Map([["sales", "core"]]);
    expect([...edgesFor(sql, "bookings", owner)]).toEqual(["core"]);
  });

  it("ignores a same-module reference", () => {
    const sql = `alter table "widgets" add constraint self_fk foreign key ("p") references "widgets"("id");`;
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual([]);
  });

  it("ignores a same-module reference in the SQLite spelling", () => {
    const sql = "FOREIGN KEY (`p`) REFERENCES `widgets`(`id`) ON UPDATE no action;";
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual([]);
  });

  // Negative control: the keyword sitting in a `--` comment must not fake an edge.
  it("ignores a reference inside a line comment", () => {
    const sql =
      "-- references `gadgets`(`id`) — describing the old shape\ncreate table `widgets` (`id` text primary key);";
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual([]);
  });

  // Negative control: the keyword inside a single-quoted string literal must not fake an edge.
  it("ignores a reference inside a string literal", () => {
    const sql = "insert into notes (body) values ('this references `gadgets` in prose');";
    expect([...edgesFor(sql, "alpha", OWNER)]).toEqual([]);
  });

  it("carries the kind and target on each edge, for a readable violation message", () => {
    const sql =
      "REFERENCES `gadgets`(`id`);\nCREATE TRIGGER `t` AFTER INSERT ON `gadgets` BEGIN SELECT 1; END;";
    expect(edgeDetails(sql, "alpha", OWNER)).toEqual([
      { dep: "beta", kind: "FK reference", target: "gadgets" },
      { dep: "beta", kind: "trigger", target: "gadgets" },
    ]);
  });
});

describe("the tree's module graph is honest", () => {
  const discovered = discoverDrizzlePackages();
  const owner = ownerOfTable(discovered);
  const modules = discovered.map((pkg) => pkg.moduleName);

  // Every cross-module edge found, keyed by kind AND target, so an anchor can pin a SPECIFIC edge
  // shape rather than just "some edge between these two modules".
  const foundEdgeDetails = new Set<string>();
  for (const pkg of discovered) {
    for (const raw of pkg.sqls) {
      for (const edge of edgeDetails(raw, pkg.moduleName, owner)) {
        foundEdgeDetails.add(`${pkg.moduleName}→${edge.dep} via ${edge.kind} on ${edge.target}`);
      }
    }
  }

  // Vacuous-pass anchor. A scan that silently matched nothing would leave `violations` empty and pass
  // — identical to every descriptor being honest. So pin that the discovery found the modules that
  // are not going away (a loose floor, not an exact count — CLAUDE.md §2) AND that the scan actually
  // resolved a known real cross-module edge in the tree's own spelling: `workforce → identity`,
  // which `packages/workforce/drizzle`'s baseline writes as ``REFERENCES `persons`(`id`)`` against
  // the `persons` table `packages/identity/drizzle` creates. It is pinned by KIND and TARGET, not
  // just as `workforce→identity`, so it stays a control for the one detector it exercises: strip the
  // backtick from the `REFERENCES` character class and this goes red.
  //
  // What this anchor does NOT cover is the trigger detector — the tree contains no trigger at all
  // since the SQLite regeneration, so that detector's only controls are the crafted cases above.
  // See the header's known limitation headed THE TRIGGER DETECTOR HAS NO TREE ANCHOR.
  it("discovers the modules and finds the known real cross-module edges", () => {
    for (const name of ["core", "identity", "payments", "workforce"]) {
      expect(modules).toContain(name);
    }
    expect(modules.length).toBeGreaterThanOrEqual(10);
    expect(foundEdgeDetails.has("workforce→identity via FK reference on persons")).toBe(true);
  });

  it("every FK/trigger edge in the SQL is named in the depending descriptor's requires", () => {
    const violations: string[] = [];
    for (const pkg of discovered) {
      const declared = declaredDepsOf(pkg.moduleName);
      for (const raw of pkg.sqls) {
        for (const edge of edgeDetails(raw, pkg.moduleName, owner)) {
          if (declared.has(edge.dep)) continue;
          const message = `${pkg.moduleName} depends on ${edge.dep} via ${edge.kind} on ${edge.target} — not in requires`;
          if (!violations.includes(message)) violations.push(message);
        }
      }
    }
    expect(violations.sort()).toEqual([]);
  });
});
