import { withdrawPendingDepartmentTransfers } from "./department-transfer-lifecycle.js";
import {
  listDepartmentTransferDestinations,
  listIncomingDepartmentTransfers,
  readIncomingDepartmentTransfer,
  listDepartmentSentTransfers,
  listSentDepartmentTransfers,
  requestDepartmentTransfer,
  readDepartmentTransfer,
  withdrawDepartmentTransfer,
  acceptDepartmentTransfer,
  declineDepartmentTransfer,
} from "./department-transfers.js";
import {
  describeMakers,
  resolveMakers,
  resolveExtraMakers,
  routingAt,
  stationStates,
} from "./routing-store.js";
import type { VenueServiceContribution } from "@waitron/module";
import {
  assertPeriodEndOffsets,
  resolveDefaultMenu,
  resolveDepartmentService,
} from "./menu-timetable.js";
import {
  copyOrderServiceContext,
  copyWorkingLineContext,
  findOrderServiceContext,
  findOrderServiceModes,
  findOrderServiceZones,
  getOrderServiceContext,
  listServiceZones,
  listZoneOffers,
  listWorkingLineContexts,
  readLinesSoldInEach,
  recordOrderServiceContext,
  retargetOrderServiceContext,
  recordWorkingLineContexts,
  resolveNewOrderZone,
  resolveSalePolicy,
  recordSaleReceiptHeader,
  readSaleReceiptHeader,
  resolveZoneContext,
  menuState,
  orderInZones,
} from "./operations.js";
import {
  acknowledgeKitchenNotice,
  listStationNotices,
  readClearingWorkflow,
  readEditSentLines,
  readKitchenTicketGrouping,
  readPrintHeldWork,
  readReleaseReminderMinutes,
  recordKitchenNotices,
} from "./kitchen-notices.js";
import {
  assertProfileBinding,
  assertProfileZone,
  readProfileKitchenLists,
  readProfileServiceAccess,
  readProfileServiceScopes,
  readProfileZones,
  setProfileKitchenLists,
  setProfileServiceScope,
} from "./profile-access.js";

/** The generic server-facing service seat; it owns no transaction and calls no server code. */
export const VENUE_SERVICE: VenueServiceContribution = {
  assertPeriodEndOffsets,
  withdrawPendingDepartmentTransfers,
  listDepartmentTransferDestinations,
  listIncomingDepartmentTransfers,
  readIncomingDepartmentTransfer,
  listDepartmentSentTransfers,
  listSentDepartmentTransfers,
  requestDepartmentTransfer,
  readDepartmentTransfer,
  withdrawDepartmentTransfer,
  acceptDepartmentTransfer,
  declineDepartmentTransfer,
  copyOrderContext: copyOrderServiceContext,
  copyLineContext: copyWorkingLineContext,
  findOrderContext: findOrderServiceContext,
  findOrderModes: findOrderServiceModes,
  findOrderZones: findOrderServiceZones,
  listLineContexts: listWorkingLineContexts,
  readLinesSoldInEach,
  listServiceZones,
  resolveZoneContext,
  resolveDepartmentService,
  resolveSalePolicy,
  recordSaleReceiptHeader,
  readSaleReceiptHeader,
  resolveMakers,
  resolveExtraMakers,
  routingAt,
  stationStates,
  describeMakers,
  listZoneOffers,
  resolveDefaultMenu,
  menuState,
  resolveNewOrderZone,
  readProfileServiceAccess,
  readProfileZones,
  assertProfileZone,
  readProfileKitchenLists,
  setProfileKitchenLists,
  readProfileServiceScopes,
  setProfileServiceScope,
  assertProfileBinding,
  orderInZones,
  recordOrderContext: recordOrderServiceContext,
  retargetOrderContext: retargetOrderServiceContext,
  recordLineContexts: recordWorkingLineContexts,
  getOrderContext: getOrderServiceContext,
  recordKitchenNotices,
  listStationNotices,
  acknowledgeKitchenNotice,
  readEditSentLines,
  readClearingWorkflow,
  readKitchenTicketGrouping,
  readPrintHeldWork,
  readReleaseReminderMinutes,
};
