import { readKeepOpen, keepPeriodOpen, keepZoneOpen } from "./keep-open.js";
import { assertZoneTakesNewOrders, closedZoneIdsAt } from "./zone-closed-times.js";
import { withdrawPendingDepartmentTransfers } from "./department-transfer-lifecycle.js";
import {
  listDepartmentTransferDestinations,
  listIncomingDepartmentTransfers,
  readIncomingDepartmentTransfer,
  listDepartmentSentTransfers,
  listSentDepartmentTransfers,
  requestDepartmentTransfer,
  readDepartmentTransfer,
  withdrawDepartmentTransfer,
  acceptDepartmentTransfer,
  declineDepartmentTransfer,
} from "./department-transfers.js";
import {
  describeMakers,
  resolveMakers,
  resolveExtraMakers,
  routingAt,
  stationStates,
} from "./routing-store.js";
import { stationDestinations, closeStationForToday, openStationForToday } from "./station-times.js";
import type { VenueServiceContribution } from "@waitron/module";
import {
  assertPeriodEndOffsets,
  resolveDefaultMenu,
  resolveDepartmentService,
} from "./menu-timetable.js";
import {
  copyOrderServiceContext,
  copyWorkingLineContext,
  findOrderServiceContext,
  findOrderServiceModes,
  findOrderServiceZones,
  getOrderServiceContext,
  listServiceZones,
  listZoneOffers,
  listWorkingLineContexts,
  readLinesSoldInEach,
  recordOrderServiceContext,
  retargetOrderServiceContext,
  recordWorkingLineContexts,
  resolveNewOrderZone,
  resolveSalePolicy,
  recordSaleReceiptHeader,
  readSaleReceiptHeader,
  resolveZoneContext,
  menuState,
  readZoneKeepOpenState,
  orderInZones,
} from "./operations.js";
import {
  acknowledgeKitchenNotice,
  listStationNotices,
  readClearingWorkflow,
  readEditSentLines,
  readKitchenTicketGrouping,
  readPrintHeldWork,
  readReleaseReminderMinutes,
  recordKitchenNotices,
} from "./kitchen-notices.js";
import {
  assertProfileZone,
  readProfileServiceAccess,
  readProfileServiceScopes,
  readProfileZones,
  setProfileServiceScope,
} from "./profile-access.js";
import {
  addProfileKitchenScreen,
  assertDeviceKitchenScreens,
  assertKitchenDisplayHasScreen,
  assertPassScreenZone,
  checkProfileKitchenScreens,
  followsEveryStation,
  narrowDeviceKitchenScreens,
  readDeviceKitchenScreens,
  readDevicesKitchenScreens,
  readProfileKitchenScreens,
  readStationScreens,
  setDeviceKitchenScreens,
  setProfileKitchenScreens,
} from "./kitchen-screens.js";

/** The generic server-facing service seat; it owns no transaction and calls no server code. */
export const VENUE_SERVICE: VenueServiceContribution = {
  assertPeriodEndOffsets,
  assertZoneTakesNewOrders,
  closedZoneIdsAt,
  withdrawPendingDepartmentTransfers,
  listDepartmentTransferDestinations,
  listIncomingDepartmentTransfers,
  readIncomingDepartmentTransfer,
  listDepartmentSentTransfers,
  listSentDepartmentTransfers,
  requestDepartmentTransfer,
  readDepartmentTransfer,
  withdrawDepartmentTransfer,
  acceptDepartmentTransfer,
  declineDepartmentTransfer,
  copyOrderContext: copyOrderServiceContext,
  copyLineContext: copyWorkingLineContext,
  findOrderContext: findOrderServiceContext,
  findOrderModes: findOrderServiceModes,
  findOrderZones: findOrderServiceZones,
  listLineContexts: listWorkingLineContexts,
  readLinesSoldInEach,
  listServiceZones,
  resolveZoneContext,
  resolveDepartmentService,
  readKeepOpen,
  keepPeriodOpen,
  keepZoneOpen,
  resolveSalePolicy,
  recordSaleReceiptHeader,
  readSaleReceiptHeader,
  resolveMakers,
  resolveExtraMakers,
  routingAt,
  stationStates,
  stationDestinations,
  closeStationForToday,
  openStationForToday,
  describeMakers,
  listZoneOffers,
  resolveDefaultMenu,
  menuState,
  readZoneKeepOpenState,
  resolveNewOrderZone,
  readProfileServiceAccess,
  readProfileZones,
  assertProfileZone,
  readProfileServiceScopes,
  setProfileServiceScope,
  readProfileKitchenScreens,
  setProfileKitchenScreens,
  checkProfileKitchenScreens,
  narrowDeviceKitchenScreens,
  addProfileKitchenScreen,
  readDeviceKitchenScreens,
  readDevicesKitchenScreens,
  setDeviceKitchenScreens,
  assertDeviceKitchenScreens,
  assertKitchenDisplayHasScreen,
  assertPassScreenZone,
  readStationScreens,
  followsEveryStation,
  orderInZones,
  recordOrderContext: recordOrderServiceContext,
  retargetOrderContext: retargetOrderServiceContext,
  recordLineContexts: recordWorkingLineContexts,
  getOrderContext: getOrderServiceContext,
  recordKitchenNotices,
  listStationNotices,
  acknowledgeKitchenNotice,
  readEditSentLines,
  readClearingWorkflow,
  readKitchenTicketGrouping,
  readPrintHeldWork,
  readReleaseReminderMinutes,
};
