export const QUERY_DEPENDENCIES = {
  health: [
    "kitchen_stations",
    "kitchen_timing_defaults",
    "kitchen_station_timing",
    "ticket_items",
    "working_order_lines",
    "working_orders",
    "party_tables",
    "dining_tables",
    "devices",
    "station_printers",
    "printers",
    "print_jobs",
  ],
  settings: ["service_settings"],
  routing: [
    "kitchen_timing_defaults",
    "kitchen_station_timing",
    "station_claims",
    "route_exceptions",
    "kitchen_stations",
    "categories",
    "category_details",
    "products",
    "floor_zones",
    "station_printers",
    "printers",
    "devices",
    "watchers",
    "watcher_stations",
    "watcher_zones",
    "watcher_printers",
    "station_fallbacks",
    "station_day_states",
    "hours_week_cells",
    "hours_week_periods",
    "special_dates",
    "special_date_hours",
    "special_date_hours_periods",
    "locations",
  ],
  hours: [
    "locations",
    "departments",
    "kitchen_stations",
    "hours_week_cells",
    "hours_week_periods",
    "special_dates",
    "special_date_hours",
    "special_date_hours_periods",
    "station_day_states",
    "station_fallbacks",
    "tenants",
    "holiday_geographies",
    "local_holidays",
  ],
  holidays: ["tenants", "locations", "holiday_geographies", "local_holidays"],
  operations: [
    "departments",
    "zone_service_policies",
    "zone_menus",
    "station_claims",
    "route_exceptions",
    "service_settings",
    "catalogues",
    "categories",
    "kitchen_stations",
    "floor_zones",
    "devices",
    "device_zone_defaults",
    "products",
    "content_languages",
    "menu_details",
    "sections",
    "section_members",
    "menu_items",
  ],
} as const;
