export const QUERY_DEPENDENCIES = {
  operations: [
    "departments",
    "zone_service_policies",
    "zone_menus",
    "preparation_routes",
    "department_hours",
    "service_settings",
    "catalogues",
    "categories",
    "kitchen_stations",
    "floor_zones",
    "products",
    "content_languages",
    "menu_details",
    "sections",
    "section_members",
    "menu_items",
  ],
} as const;
