import { makeT, registerCatalogue } from "@waitron/dashboard-kit";

const en = {
  "nav.prep_stations": "Prep stations",
  "prep.title": "Prep stations",
  "prep.new_station": "New station",
  "prep.edit_station": "Edit station",
  "prep.name": "Name",
  "prep.order": "Display order",
  "prep.warm": "Warm after (min)",
  "prep.overdue": "Overdue after (min)",
  "prep.forgotten": "Forgotten after (min)",
  "prep.default": "Default",
  "prep.make_default": "Make default",
  "prep.edit": "Edit",
  "prep.switch_off": "Switch off",
  "prep.no_preparation": "No preparation",
  "prep.claims": "Claims:",
  "prep.claim_folder": "Claim a folder",
  "prep.remove_claim": "Remove claim",
  "prep.folder": "Folder",
  "prep.unassigned": "Unassigned",
  "prep.assign_to": "Assign to…",
  "prep.product_unassigned": "Assign its folder or add an exception",
  "prep.fallback": "These go to the default station, {name}.",
  "prep.switched_off": "Switched off",
  "prep.switched_off_hint": "Switched off: its work goes to the next rule",
  "prep.printers": "Printers",
  "prep.printing_rules": "Printing rules",
  "prep.screens": "Kitchen screens",
  "prep.devices": "Devices",
  "prep.none": "None",
  "prep.thresholds": "Warm {warm} min · Overdue {overdue} min · Forgotten {forgotten} min",
  "prep.name_required": "Enter a name.",
  "prep.name_taken": "This name is already in use.",
  "prep.order_invalid": "Enter a whole number of zero or more.",
  "prep.threshold_invalid": "Use whole minutes with warm < overdue < forgotten.",
  "prep.save": "Save",
  "prep.cancel": "Cancel",
  "prep.load_error": "Prep stations could not be loaded.",
  "prep.save_error": "The change could not be saved.",
  "prep.fix_fields": "Correct the highlighted fields to continue.",
  "prep.station_inactive": "This station is switched off. Choose an active station.",
  "prep.exceptions": "Exceptions",
  "prep.add_exception": "Add exception",
  "prep.edit_exception": "Edit exception",
  "prep.confirm_delete_exception": "Delete exception?",
  "prep.delete": "Delete",
  "prep.actions": "Actions",
  "prep.exception_rule": "Rule",
  "prep.reorder_exception": "Reorder exception",
  "prep.reordered": "{item} moved to position {index} of {total}",
  "prep.never_used": "Never used: an exception above always catches it first",
  "prep.exception_station_off": "Its station is switched off",
  "prep.what": "What",
  "prep.everything": "Everything",
  "prep.service_zone": "Service zone",
  "prep.any_zone": "Any service zone",
  "prep.made_at": "Made at",
  "prep.exception_condition": "Choose a folder or product, a service zone, or both",
  "prep.exception_target_required": "Choose where this is made.",
  "venue.department_has_zones":
    "Move its active service zones to another department before deactivating this department.",
  "venue.status": "Status",
  "venue.active": "Active",
  "venue.inactive": "Inactive",
  "venue.edit": "Edit",
  "venue.delete": "Delete",
  "venue.save": "Save",
  "venue.cancel": "Cancel",
  "venue.confirm": "Confirm",
  "venue.confirm_remove": "Confirm removal",
  "venue.no_rows": "No entries yet.",
  "venue.zone": "Service zone",
  "venue.unconfigured": "Not configured",
  "venue.yes": "Yes",
  "venue.no": "No",
  "venue.display_order": "Display order",
  "venue.edit_department": "Edit department",
  "venue.edit_hours": "Edit hours",
  "venue.edit_assignment": "Edit menu assignment",
  "venue.order_invalid": "Enter a whole number of zero or more.",

  "nav.venue_operations": "Venue operations",
  "venue.title": "Venue operations",
  "venue.departments": "Departments",
  "venue.add_department": "Add department",
  "venue.name": "Department name",
  "venue.trading_name": "Trading name",
  "venue.service_style": "Service style",
  "venue.table_tab": "Table service",
  "venue.prepay": "Pay before preparation",
  "venue.invoice_first": "Pay then prepare",
  "venue.ticket_then_pay": "Prepare then pay",
  "venue.zones": "Service zones and menus",
  "venue.department": "Department",
  "venue.inherit": "Use department default",
  "venue.save_zone": "Save zone",
  "venue.make_available": "Make available",
  "venue.make_default": "Make default",
  "venue.default": "Default",
  "venue.hours": "Opening hours",
  "venue.menus": "Menus",
  "venue.menu_name": "Menu name",
  "venue.actions": "Actions",
  "venue.columns": "Columns",
  "venue.weekday": "Day",
  "venue.opens": "Opens",
  "venue.closes": "Closes",
  "venue.add_hours": "Add hours",
  "venue.required": "Fill in every required field.",
  "venue.fix_fields": "Correct the highlighted fields to continue.",
  "venue.field_required": "This field is required.",
  "venue.field_refused": "This value was not accepted. Change it and save again.",
  "venue.time_distinct": "Opening and closing times must differ.",
  "venue.day.0": "Sunday",
  "venue.day.1": "Monday",
  "venue.day.2": "Tuesday",
  "venue.day.3": "Wednesday",
  "venue.day.4": "Thursday",
  "venue.day.5": "Friday",
  "venue.day.6": "Saturday",
  "venue.load_error": "The venue configuration could not be loaded.",
  "venue.save_error": "The change could not be saved.",
  "venue.empty": "No departments have been configured.",
  "venue.readiness": "Ready for service",
  "venue.readiness.ok": "Every active service zone is ready to take orders.",
  "venue.readiness.department_missing": "Create an active department before service.",
  "venue.readiness.default_station_missing":
    "No default prep station is switched on. Items no rule sends anywhere cannot be sent.",
  "venue.readiness.zone_department_missing": "needs an active department.",
  "venue.readiness.zone_menu_missing": "needs a default menu.",
  "venue.readiness.menu_empty": "has no products for",
  "venue.readiness.zone_menu_unpublished": "needs an active, published menu.",
  "venue.deactivate_department": "Deactivate department",
  "venue.kitchen_changes": "Changes after sending",
  "venue.edit_sent_lines": "Allow changes to items already sent to the kitchen",
  "venue.edit_sent_lines_hint":
    "When off, staff cannot change or recall an item the kitchen already has; they cancel it instead.",
  "venue.kitchen_ticket_grouping": "Identical dishes on a kitchen ticket",
  "venue.kitchen_ticket_grouping.combined": "One line: 3 x Burger",
  "venue.kitchen_ticket_grouping.separate": "A line each: 1 x Burger, three times",
  "venue.kitchen_ticket_grouping_hint": "Applies to new kitchen tickets and to reprints.",
  "venue.release_reminder": "Reminder to fire the next group",
  "venue.release_reminder.off": "Off",
  "venue.release_reminder.minutes": "{n} minutes",
  "venue.release_reminder_hint":
    "Counted from when every group fired before the next held group has been marked served. Staff can snooze it from the table.",
  "venue.print_held_work": "Print held groups in advance",
  "venue.print_held_work_hint":
    "A held group prints straight away on a kitchen ticket marked HOLD. Adding, moving, removing or changing its dishes then prints a HOLD correction, and firing it prints its ticket marked FIRE. A group held before this is turned on prints when it is fired, as before. A group already printed marked HOLD is still fired marked FIRE after this is turned off.",
} as const;

const es: Record<keyof typeof en, string> = {
  "nav.prep_stations": "Estaciones de preparación",
  "prep.title": "Estaciones de preparación",
  "prep.new_station": "Nueva estación",
  "prep.edit_station": "Editar estación",
  "prep.name": "Nombre",
  "prep.order": "Orden de visualización",
  "prep.warm": "Aviso a partir de (min)",
  "prep.overdue": "Atraso a partir de (min)",
  "prep.forgotten": "Olvido a partir de (min)",
  "prep.default": "Predeterminada",
  "prep.make_default": "Hacer predeterminada",
  "prep.edit": "Editar",
  "prep.switch_off": "Desactivar",
  "prep.no_preparation": "Sin preparación",
  "prep.claims": "Asignaciones:",
  "prep.claim_folder": "Asignar una carpeta",
  "prep.remove_claim": "Quitar asignación",
  "prep.folder": "Carpeta",
  "prep.unassigned": "Sin asignar",
  "prep.assign_to": "Asignar a…",
  "prep.product_unassigned": "Asigna su carpeta o añade una excepción",
  "prep.fallback": "Estos van a la estación predeterminada, {name}.",
  "prep.switched_off": "Desactivadas",
  "prep.switched_off_hint": "Desactivada: su trabajo pasa a la siguiente regla",
  "prep.printers": "Impresoras",
  "prep.printing_rules": "Reglas de impresión",
  "prep.screens": "Pantallas de cocina",
  "prep.devices": "Dispositivos",
  "prep.none": "Ninguno",
  "prep.thresholds": "Aviso {warm} min · Atraso {overdue} min · Olvido {forgotten} min",
  "prep.name_required": "Escribe un nombre.",
  "prep.name_taken": "Este nombre ya está en uso.",
  "prep.order_invalid": "Escribe un número entero no negativo.",
  "prep.threshold_invalid": "Usa minutos enteros con aviso < atraso < olvido.",
  "prep.save": "Guardar",
  "prep.cancel": "Cancelar",
  "prep.load_error": "No se pudieron cargar las estaciones de preparación.",
  "prep.save_error": "No se pudo guardar el cambio.",
  "prep.fix_fields": "Corrige los campos marcados para continuar.",
  "prep.station_inactive": "Esta estación está desactivada. Elige una estación activa.",
  "prep.exceptions": "Excepciones",
  "prep.add_exception": "Añadir excepción",
  "prep.edit_exception": "Editar excepción",
  "prep.confirm_delete_exception": "¿Eliminar excepción?",
  "prep.delete": "Eliminar",
  "prep.actions": "Acciones",
  "prep.exception_rule": "Regla",
  "prep.reorder_exception": "Reordenar excepción",
  "prep.reordered": "{item} movida a la posición {index} de {total}",
  "prep.never_used": "Nunca se usa: una excepción anterior siempre coincide primero",
  "prep.exception_station_off": "Su estación está desactivada",
  "prep.what": "Qué",
  "prep.everything": "Todo",
  "prep.service_zone": "Zona de servicio",
  "prep.any_zone": "Cualquier zona de servicio",
  "prep.made_at": "Se prepara en",
  "prep.exception_condition": "Elige una carpeta o producto, una zona de servicio, o ambos",
  "prep.exception_target_required": "Elige dónde se prepara.",
  "venue.department_has_zones":
    "Mueve sus zonas de servicio activas a otro departamento antes de desactivar este departamento.",
  "venue.status": "Estado",
  "venue.active": "Activo",
  "venue.inactive": "Inactivo",
  "venue.edit": "Editar",
  "venue.delete": "Eliminar",
  "venue.save": "Guardar",
  "venue.cancel": "Cancelar",
  "venue.confirm": "Confirmar",
  "venue.confirm_remove": "Confirmar eliminación",
  "venue.no_rows": "Todavía no hay entradas.",
  "venue.zone": "Zona de servicio",
  "venue.unconfigured": "Sin configurar",
  "venue.yes": "Sí",
  "venue.no": "No",
  "venue.display_order": "Orden de visualización",
  "venue.edit_department": "Editar departamento",
  "venue.edit_hours": "Editar horario",
  "venue.edit_assignment": "Editar asignación de carta",
  "venue.order_invalid": "Introduce un número entero igual o mayor que cero.",

  "nav.venue_operations": "Operaciones del local",
  "venue.title": "Operaciones del local",
  "venue.departments": "Departamentos",
  "venue.add_department": "Añadir departamento",
  "venue.name": "Nombre del departamento",
  "venue.trading_name": "Nombre comercial",
  "venue.service_style": "Estilo de servicio",
  "venue.table_tab": "Servicio de mesa",
  "venue.prepay": "Pagar antes de preparar",
  "venue.invoice_first": "Pagar y después preparar",
  "venue.ticket_then_pay": "Preparar y después pagar",
  "venue.zones": "Zonas de servicio y cartas",
  "venue.department": "Departamento",
  "venue.inherit": "Usar el valor del departamento",
  "venue.save_zone": "Guardar zona",
  "venue.make_available": "Hacer disponible",
  "venue.make_default": "Establecer por defecto",
  "venue.default": "Por defecto",
  "venue.hours": "Horario de apertura",
  "venue.menus": "Cartas",
  "venue.menu_name": "Nombre de la carta",
  "venue.actions": "Acciones",
  "venue.columns": "Columnas",
  "venue.weekday": "Día",
  "venue.opens": "Abre",
  "venue.closes": "Cierra",
  "venue.add_hours": "Añadir horario",
  "venue.required": "Completa todos los campos obligatorios.",
  "venue.fix_fields": "Corrige los campos marcados para continuar.",
  "venue.field_required": "Este campo es obligatorio.",
  "venue.field_refused": "No se ha aceptado este valor. Cámbialo y vuelve a guardar.",
  "venue.time_distinct": "Las horas de apertura y cierre deben ser distintas.",
  "venue.day.0": "Domingo",
  "venue.day.1": "Lunes",
  "venue.day.2": "Martes",
  "venue.day.3": "Miércoles",
  "venue.day.4": "Jueves",
  "venue.day.5": "Viernes",
  "venue.day.6": "Sábado",
  "venue.load_error": "No se pudo cargar la configuración del local.",
  "venue.save_error": "No se pudo guardar el cambio.",
  "venue.empty": "No hay departamentos configurados.",
  "venue.readiness": "Preparado para el servicio",
  "venue.readiness.ok": "Todas las zonas activas están preparadas para aceptar pedidos.",
  "venue.readiness.department_missing": "Crea un departamento activo antes del servicio.",
  "venue.readiness.default_station_missing":
    "Ninguna estación de preparación predeterminada está activa. Los artículos que ninguna regla envía a una estación no se pueden enviar.",
  "venue.readiness.zone_department_missing": "necesita un departamento activo.",
  "venue.readiness.zone_menu_missing": "necesita una carta predeterminada.",
  "venue.readiness.menu_empty": "no tiene productos para",
  "venue.readiness.zone_menu_unpublished": "necesita una carta activa y publicada.",
  "venue.deactivate_department": "Desactivar departamento",
  "venue.kitchen_changes": "Cambios tras el envío",
  "venue.edit_sent_lines": "Permitir cambios en los artículos ya enviados a cocina",
  "venue.edit_sent_lines_hint":
    "Si está desactivado, el personal no puede cambiar ni retirar un artículo que ya tiene la cocina; tiene que cancelarlo.",
  "venue.kitchen_ticket_grouping": "Platos iguales en una comanda de cocina",
  "venue.kitchen_ticket_grouping.combined": "Una línea: 3 x Hamburguesa",
  "venue.kitchen_ticket_grouping.separate": "Una por plato: 1 x Hamburguesa, tres veces",
  "venue.kitchen_ticket_grouping_hint":
    "Se aplica a las comandas de cocina nuevas y a las reimpresiones.",
  "venue.release_reminder": "Aviso para marchar el siguiente grupo",
  "venue.release_reminder.off": "Desactivado",
  "venue.release_reminder.minutes": "{n} minutos",
  "venue.release_reminder_hint":
    "Se cuenta desde que cada grupo marchado antes del siguiente grupo en espera se ha marcado como servido. El personal puede posponerlo desde la mesa.",
  "venue.print_held_work": "Imprimir por adelantado los grupos en espera",
  "venue.print_held_work_hint":
    "Un grupo en espera se imprime en el momento en una comanda de cocina marcada HOLD. Añadir, mover, quitar o cambiar sus platos imprime después una corrección HOLD, y al marcharlo se imprime su comanda marcada FIRE. Un grupo que ya estaba en espera antes de activarlo se imprime al marcharlo, como hasta ahora. Un grupo ya impreso como HOLD se sigue marchando marcado FIRE aunque se desactive.",
};

export const VENUE_SERVICE_STRINGS = { en, es };
registerCatalogue(VENUE_SERVICE_STRINGS);
export const t = makeT<keyof typeof en>();
