import { makeT, registerCatalogue } from "@waitron/dashboard-kit";

const en = {
  "watchers.title": "Watchers",
  "watchers.new": "New watcher",
  "watchers.follows": "Follows: {list}",
  "watchers.every_station": "every station",
  "watchers.choose_every_station": "Every station",
  "watchers.for": "For: {list}",
  "watchers.every_zone": "every service zone",
  "watchers.choose_every_zone": "Every service zone",
  "watchers.runs_pass": "Runs the pass",
  "watchers.runs_pass_hint":
    "Shows Fire (when the pass fires held work), Ready and Away for whole courses and groups.",
  "watchers.fix_fields": "Fix the fields marked above.",
  "watchers.screens": "Screens",
  "watchers.printers": "Printers",
  "watchers.remove_confirm":
    "Remove {name}? Its screens will say it was removed, and its printers stop printing its copies.",
  "watchers.need_station": "Choose at least one station, or every station",
  "watchers.need_zone": "Choose at least one service zone, or every service zone",
  "watchers.watched_by": "Watched by: {list}",
  "watchers.none_follow": "No watcher follows it.",
  "watchers.name_taken": "A watcher already has this name.",
  "watchers.not_found": "This watcher could not be found.",
  "watchers.stations": "Stations",
  "watchers.zones": "Service zones",
  "watchers.remove": "Remove",
  "nav.prep_stations": "Prep stations",
  "prep.title": "Prep stations",
  "prep.new_station": "New station",
  "prep.edit_station": "Edit station",
  "prep.name": "Name",
  "prep.order": "Display order",
  "prep.warm": "Warm after (min)",
  "prep.overdue": "Overdue after (min)",
  "prep.forgotten": "Forgotten after (min)",
  "prep.default": "Default",
  "prep.make_default": "Make default",
  "prep.edit": "Edit",
  "prep.switch_off": "Switch off",
  "prep.switch_on": "Switch on",
  "prep.open_now": "Open now",
  "prep.opened_by_hand": "Open now, opened by hand until {time} {day}",
  "prep.closed_hours": "Closed now: outside its opening hours. {destination}",
  "prep.closed_by_hand": "Closed now, closed by hand until {time} {day}. {destination}",
  "prep.always_open_default": "Always open: this is the default station",
  "prep.clock_unreadable":
    "Opening hours are not applied: the venue's time zone or day cutover cannot be read.",
  "prep.work_goes_to": "Its work goes to {station}.",
  "prep.no_replacement_ask": "No replacement: the till will ask where to send its dishes.",
  "prep.today": "today",
  "prep.tomorrow": "tomorrow",
  "prep.close_today": "Close for today",
  "prep.open_today": "Open for today",
  "prep.back_to_schedule": "Back to the schedule",
  "prep.close_confirm": "{station}'s work goes to {destination} until {time} {day}.",
  "prep.close_confirm_ask":
    "While {station} is closed, the till will ask where to send its dishes, until {time} {day}.",
  "prep.edit_hours": "Edit hours",
  "prep.always_open": "Always open",
  "prep.next_day": "(next day)",
  "prep.weekday": "Weekday",
  "prep.opens_at": "Opens at",
  "prep.closes_at": "Closes at",
  "prep.until_next_day": "until {time} the next day",
  "prep.remove_hours": "Remove hours",
  "prep.add_hours": "Add hours",
  "prep.search_stations": "Search stations",
  "prep.when_closed": "When closed, work goes to",
  "prep.no_replacement_choice": "No replacement (the till asks)",
  "prep.switched_off_option": "(switched off)",
  "prep.change_fallback": "Change where its work goes",
  "prep.fallback_confirm": "While {station} is closed, its work will go to {destination}.",
  "prep.fallback_confirm_ask":
    "While {station} is closed, the till will ask where to send its dishes.",
  "prep.starts_now": "That starts now.",
  "prep.fallback_closed_too":
    "{station} is closed now as well, so for now it goes to {destination}.",
  "prep.fallback_closed_ask":
    "{station} is closed now as well and has no replacement, so for now the till will ask.",
  "prep.switch_off_confirm": "Switch off {station}? Its work will go to:",
  "prep.off_goes_to": "Its work goes to {station}.",
  "prep.off_asks": "No replacement: the till asks.",
  "prep.switched_off_no_replacement": "Switched off: no replacement, the till asks",
  "prep.printer_down":
    "Printer {printer} has printed nothing since something sent to it at {time} got stuck.",
  "prep.screen_dark": "Dishes are waiting, and no kitchen screen here has checked in since {time}.",
  "prep.screen_never": "Dishes are waiting, and no kitchen screen here has ever checked in.",
  "prep.fallback_loop": "This replacement would create a loop. Choose another station.",
  "prep.time_zone_unreadable": "The venue's time zone or day cutover cannot be read.",
  "prep.station_not_found": "This station could not be found.",
  "prep.no_preparation": "No preparation",
  "prep.claims": "Claims:",
  "prep.claim_folder": "Claim a folder",
  "prep.remove_claim": "Remove claim",
  "prep.folder": "Folder",
  "prep.unassigned": "Unassigned",
  "prep.assign_to": "Assign to…",
  "prep.product_unassigned": "Assign its folder or add an exception",
  "prep.fallback": "These go to the default station, {name}.",
  "prep.switched_off": "Switched off",
  "prep.inactive_station_label": "Switched off",
  "prep.switched_off_hint": "Switched off: its work goes to its fallback",
  "prep.printers": "Printers",
  "prep.printing_rules": "Printing rules",
  "prep.screens": "Kitchen screens",
  "prep.devices": "Devices",
  "prep.none": "None",
  "prep.thresholds": "Warm {warm} min · Overdue {overdue} min · Forgotten {forgotten} min",
  "prep.shows_rest_of_order": "Show the rest of the order",
  "prep.shows_rest_of_order_hint":
    "Its tickets and kitchen screen also list the order's dishes at other stations.",
  "prep.name_required": "Enter a name.",
  "prep.name_taken": "This name is already in use.",
  "prep.order_invalid": "Enter a whole number of zero or more.",
  "prep.threshold_invalid": "Use whole minutes with warm < overdue < forgotten.",
  "prep.save": "Save",
  "prep.cancel": "Cancel",
  "prep.confirm": "Confirm",
  "prep.preview_title": "Review routing change",
  "prep.preview_moves": "These products will be made somewhere else:",
  "prep.preview_none": "No product changes where it is made.",
  "prep.preview_product": "Product",
  "prep.preview_from": "From",
  "prep.preview_to": "To",
  "prep.no_station": "No station",
  "prep.no_replacement": "No replacement",
  "prep.claim_move": "{folder} is claimed by {from}; this moves it to {to}.",
  "prep.load_error": "Prep stations could not be loaded.",
  "prep.save_error": "The change could not be saved.",
  "prep.fix_fields": "Correct the highlighted fields to continue.",
  "prep.station_inactive": "This station is switched off. Choose an active station.",
  "prep.exceptions": "Exceptions",
  "prep.add_exception": "Add exception",
  "prep.edit_exception": "Edit exception",
  "prep.confirm_delete_exception": "Delete exception?",
  "prep.delete": "Delete",
  "prep.actions": "Actions",
  "prep.exception_rule": "Rule",
  "prep.reorder_exception": "Reorder exception",
  "prep.reordered": "{item} moved to position {index} of {total}",
  "prep.never_used": "Never used: an exception above always catches it first",
  "prep.exception_station_off": "Its station is switched off",
  "prep.what": "What",
  "prep.everything": "Everything",
  "prep.exception_from_zone": " from {zone}",
  "prep.exception_sentence": "{what}{zone} → {target}",
  "prep.service_zone": "Service zone",
  "prep.any_zone": "Any service zone",
  "prep.made_at": "Made at",
  "prep.test_when": "When",
  "prep.test_now": "Now",
  "prep.test_at": "Weekday and time",
  "prep.test_time": "Time",
  "prep.test_time_required": "Choose a time.",
  "prep.test_out_of_hours": "{station} is closed outside its opening hours",
  "prep.test_closed_by_hand": "{station} is closed by hand today",
  "prep.test_switched_off": "{station} is switched off",
  "prep.test_fallback_step": "{reason}, so its work goes to {destination}.",
  "prep.test_no_replacement":
    "{reason}, and it has no replacement, so the till asks the waiter where to make this.",
  "prep.test_clock_unreadable":
    "The venue's time zone or day cutover cannot be read, so opening hours are not applied.",
  "prep.test_title": "Where is this made?",
  "prep.test_extras_chosen": "Extras chosen",
  "prep.test_choose_extra": "Choose an extra",
  "prep.test_remove_extra": "Remove {name}",
  "prep.test_extras_wait": "Extras: decided once the dish has a station to go to",
  "prep.test_extra_made": "{name}: made at {station}, because {reason}",
  "prep.test_extra_claim": "{station} claims {folder}",
  "prep.test_extra_exception": "of the exception '{rule}'",
  "prep.test_extra_no_rule": "{name}: follows the dish — no exception or claim covers it",
  "prep.test_extra_no_preparation":
    "{name}: follows the dish — what covers it needs no preparation, so it stays on the dish's ticket",
  "prep.test_extra_no_replacement":
    "{name}: follows the dish — {station} is closed and nothing can replace it",
  "prep.test_extra_same_station":
    "{name}: follows the dish — it is made at {dishStation}, where the dish is",
  "prep.test_product": "Product",
  "prep.test_choose_product": "Choose a product",
  "prep.test_no_zone": "No service zone",
  "prep.test_made_at": "Made at",
  "prep.test_because": "Because",
  "prep.test_claim": "{station} claims {folder}",
  "prep.test_no_prep_claim": "{folder} is assigned to {target}",
  "prep.test_exception": "the exception '{rule}'",
  "prep.test_default": "nothing else matched, so the default station takes it",
  "prep.test_no_route":
    "Nothing can make this: no rule matched and no default station is switched on.",
  "prep.test_error": "The route could not be checked.",
  "prep.exception_condition": "Choose a folder or product, a service zone, or both",
  "prep.exception_target_required": "Choose where this is made.",
  "venue.department_has_zones":
    "Move its active service zones to another department before deactivating this department.",
  "venue.status": "Status",
  "venue.active": "Active",
  "venue.inactive": "Inactive",
  "venue.edit": "Edit",
  "venue.delete": "Delete",
  "venue.save": "Save",
  "venue.cancel": "Cancel",
  "venue.confirm": "Confirm",
  "venue.confirm_remove": "Confirm removal",
  "venue.no_departments": "No departments yet.",
  "venue.no_hours": "No opening hours yet.",
  "venue.no_zones": "No service zones yet.",
  "venue.no_tills": "No active tills.",
  "venue.no_zone_menus": "No menus in this service zone yet.",
  "venue.zone": "Service zone",
  "venue.unconfigured": "Not configured",
  "venue.yes": "Yes",
  "venue.no": "No",
  "venue.display_order": "Display order",
  "venue.edit_department": "Edit department",
  "venue.edit_hours": "Edit hours",
  "venue.edit_assignment": "Edit menu assignment",
  "venue.order_invalid": "Enter a whole number of zero or more.",

  "nav.departments_zones": "Departments and zones",
  "venue.title": "Departments and zones",
  "venue.departments": "Departments",
  "venue.add_department": "Add department",
  "venue.name": "Department name",
  "venue.trading_name": "Trading name",
  "venue.service_style": "Service style",
  "venue.table_tab": "Table service",
  "venue.prepay": "Pay before preparation",
  "venue.invoice_first": "Pay then prepare",
  "venue.ticket_then_pay": "Prepare then pay",
  "venue.zones": "Service zones and menus",
  "venue.tills": "Tills",
  "venue.starts_in": "Starts in",
  "venue.counter_zone": "The venue's counter zone",
  "venue.department": "Department",
  "venue.inherit": "Use department default",
  "venue.save_zone": "Save zone",
  "venue.make_available": "Make available",
  "venue.make_default": "Make default",
  "venue.default": "Default",
  "venue.hours": "Opening hours",
  "venue.menus": "Menus",
  "venue.menu_name": "Menu name",
  "venue.actions": "Actions",
  "venue.customise_columns": "Customise columns",
  "venue.customise": "Customise",
  "venue.restore_columns": "Restore defaults",
  "venue.done": "Done",
  "venue.move_column": "Move",
  "venue.show_column": "Show",
  "venue.hide_column": "Hide",
  "venue.column_always_shown": "Always shown",
  "venue.column_last_shown": "Keep at least one shown",
  "venue.column_position": "{position} of {total}",
  "venue.weekday": "Day",
  "venue.opens": "Opens",
  "venue.closes": "Closes",
  "venue.add_hours": "Add hours",
  "venue.required": "Fill in every required field.",
  "venue.fix_fields": "Correct the highlighted fields to continue.",
  "venue.field_required": "This field is required.",
  "venue.field_refused": "This value was not accepted. Change it and save again.",
  "prep.time_required": "An opening and closing time are required.",
  "venue.time_distinct": "Opening and closing times must differ.",
  "venue.day.0": "Sunday",
  "venue.day.1": "Monday",
  "venue.day.2": "Tuesday",
  "venue.day.3": "Wednesday",
  "venue.day.4": "Thursday",
  "venue.day.5": "Friday",
  "venue.day.6": "Saturday",
  "venue.load_error": "The venue configuration could not be loaded.",
  "venue.save_error": "The change could not be saved.",
  "venue.readiness": "Ready for service",
  "venue.readiness.ok": "Every active service zone is ready to take orders.",
  "venue.readiness.department_missing": "Create an active department before service.",
  "venue.readiness.default_station_missing":
    "No default prep station is switched on. Items no rule sends anywhere cannot be sent.",
  "venue.readiness.zone_department_missing": "needs an active department.",
  "venue.readiness.zone_menu_missing": "needs a default menu.",
  "venue.readiness.menu_empty": "has no products for",
  "venue.readiness.zone_menu_unpublished": "needs an active, published menu.",
  "venue.deactivate_department": "Deactivate department",
  "venue.kitchen_changes": "Changes after sending",
  "venue.edit_sent_lines": "Allow changes to items already sent to the kitchen",
  "venue.edit_sent_lines_hint":
    "When off, staff cannot change or recall an item the kitchen already has; they cancel it instead.",
  "venue.kitchen_ticket_grouping": "Identical dishes on a kitchen ticket",
  "venue.kitchen_ticket_grouping.combined": "One line: 3 x Burger",
  "venue.kitchen_ticket_grouping.separate": "A line each: 1 x Burger, three times",
  "venue.kitchen_ticket_grouping_hint": "Applies to new kitchen tickets and to reprints.",
  "venue.release_reminder": "Reminder to fire the next group",
  "venue.release_reminder.off": "Off",
  "venue.release_reminder.minutes": "{n} minutes",
  "venue.release_reminder_hint":
    "Counted from when every group fired before the next held group has been marked served. Staff can snooze it from the table.",
  "venue.print_held_work": "Print held groups in advance",
  "venue.print_held_work_hint":
    "A held group prints straight away on a kitchen ticket marked HOLD. Adding, moving, removing or changing its dishes then prints a HOLD correction, and firing it prints its ticket marked FIRE. A group held before this is turned on prints when it is fired, as before. A group already printed marked HOLD is still fired marked FIRE after this is turned off.",
  "venue.clearing_workflow": "Needs clearing",
  "venue.clearing_workflow_hint":
    "When on, a table a party leaves — at Finish table, or by moving to another table or joining another party — shows Needs clearing until someone marks it cleared.",
  "venue.combobox_search": "Search",
  "venue.combobox_no_results": "No results",
  "venue.decrease": "Decrease {label}",
  "venue.increase": "Increase {label}",
} as const;

const es: Record<keyof typeof en, string> = {
  "watchers.title": "Puntos de seguimiento",
  "watchers.new": "Nuevo punto de seguimiento",
  "watchers.follows": "Sigue: {list}",
  "watchers.every_station": "todas las estaciones",
  "watchers.choose_every_station": "Todas las estaciones",
  "watchers.for": "Para: {list}",
  "watchers.every_zone": "todas las zonas de servicio",
  "watchers.choose_every_zone": "Todas las zonas de servicio",
  "watchers.runs_pass": "Lleva el pase",
  "watchers.runs_pass_hint":
    "Muestra Marchar (cuando el pase marcha el trabajo retenido), Listo y En camino para cursos y grupos enteros.",
  "watchers.fix_fields": "Corrige los campos marcados arriba.",
  "watchers.screens": "Pantallas",
  "watchers.printers": "Impresoras",
  "watchers.remove_confirm":
    "¿Eliminar {name}? Sus pantallas dirán que se ha eliminado y sus impresoras dejarán de imprimir sus copias.",
  "watchers.need_station": "Elige al menos una estación, o todas",
  "watchers.need_zone": "Elige al menos una zona de servicio, o todas",
  "watchers.watched_by": "Lo siguen: {list}",
  "watchers.none_follow": "Ningún punto de seguimiento lo sigue.",
  "watchers.name_taken": "Ya existe un punto de seguimiento con este nombre.",
  "watchers.not_found": "No se encontró este punto de seguimiento.",
  "watchers.stations": "Estaciones",
  "watchers.zones": "Zonas de servicio",
  "watchers.remove": "Eliminar",
  "nav.prep_stations": "Estaciones de preparación",
  "prep.title": "Estaciones de preparación",
  "prep.new_station": "Nueva estación",
  "prep.edit_station": "Editar estación",
  "prep.name": "Nombre",
  "prep.order": "Orden de visualización",
  "prep.warm": "Aviso a partir de (min)",
  "prep.overdue": "Atraso a partir de (min)",
  "prep.forgotten": "Olvido a partir de (min)",
  "prep.default": "Predeterminada",
  "prep.make_default": "Hacer predeterminada",
  "prep.edit": "Editar",
  "prep.switch_off": "Desactivar",
  "prep.switch_on": "Activar",
  "prep.open_now": "Abierta ahora",
  "prep.opened_by_hand": "Abierta ahora, abierta manualmente hasta las {time} de {day}",
  "prep.closed_hours": "Cerrada ahora: fuera del horario de apertura. {destination}",
  "prep.closed_by_hand":
    "Cerrada ahora, cerrada manualmente hasta las {time} de {day}. {destination}",
  "prep.always_open_default": "Siempre abierta: es la estación predeterminada",
  "prep.clock_unreadable":
    "No se aplica el horario de apertura: no se puede leer la zona horaria o el corte del día del local.",
  "prep.work_goes_to": "Su trabajo va a {station}.",
  "prep.no_replacement_ask": "Sin sustituta: el TPV preguntará dónde enviar sus platos.",
  "prep.today": "hoy",
  "prep.tomorrow": "mañana",
  "prep.close_today": "Cerrar por hoy",
  "prep.open_today": "Abrir por hoy",
  "prep.back_to_schedule": "Volver al horario",
  "prep.close_confirm": "El trabajo de {station} irá a {destination} hasta las {time} de {day}.",
  "prep.close_confirm_ask":
    "Mientras {station} esté cerrada, el TPV preguntará dónde enviar sus platos, hasta las {time} de {day}.",
  "prep.edit_hours": "Editar horario",
  "prep.always_open": "Siempre abierta",
  "prep.next_day": "(día siguiente)",
  "prep.weekday": "Día de la semana",
  "prep.opens_at": "Abre a las",
  "prep.closes_at": "Cierra a las",
  "prep.until_next_day": "hasta las {time} del día siguiente",
  "prep.remove_hours": "Quitar horario",
  "prep.add_hours": "Añadir horario",
  "prep.search_stations": "Buscar estaciones",
  "prep.when_closed": "Cuando está cerrada, el trabajo va a",
  "prep.no_replacement_choice": "Sin sustituta (el TPV pregunta)",
  "prep.switched_off_option": "(desactivada)",
  "prep.change_fallback": "Cambiar el destino de su trabajo",
  "prep.fallback_confirm": "Mientras {station} esté cerrada, su trabajo irá a {destination}.",
  "prep.fallback_confirm_ask":
    "Mientras {station} esté cerrada, el TPV preguntará dónde enviar sus platos.",
  "prep.starts_now": "Eso comienza ahora.",
  "prep.fallback_closed_too":
    "{station} también está cerrada ahora, así que por ahora va a {destination}.",
  "prep.fallback_closed_ask":
    "{station} también está cerrada ahora y no tiene sustituta, así que por ahora el TPV preguntará.",
  "prep.switch_off_confirm": "¿Desactivar {station}? Su trabajo irá a:",
  "prep.off_goes_to": "Su trabajo va a {station}.",
  "prep.off_asks": "Sin sustituta: el TPV pregunta.",
  "prep.switched_off_no_replacement": "Desactivada: sin sustituta, el TPV pregunta",
  "prep.printer_down":
    "La impresora {printer} no ha impreso nada desde que se atascó un envío a las {time}.",
  "prep.screen_dark":
    "Hay platos esperando y ninguna pantalla de cocina aquí ha conectado desde las {time}.",
  "prep.screen_never": "Hay platos esperando y ninguna pantalla de cocina aquí ha conectado nunca.",
  "prep.fallback_loop": "Esta sustituta crearía un bucle. Elige otra estación.",
  "prep.time_zone_unreadable": "No se puede leer la zona horaria o el corte del día del local.",
  "prep.station_not_found": "No se encontró esta estación.",
  "prep.no_preparation": "Sin preparación",
  "prep.claims": "Asignaciones:",
  "prep.claim_folder": "Asignar una carpeta",
  "prep.remove_claim": "Quitar asignación",
  "prep.folder": "Carpeta",
  "prep.unassigned": "Sin asignar",
  "prep.assign_to": "Asignar a…",
  "prep.product_unassigned": "Asigna su carpeta o añade una excepción",
  "prep.fallback": "Estos van a la estación predeterminada, {name}.",
  "prep.switched_off": "Desactivadas",
  "prep.inactive_station_label": "Desactivada",
  "prep.switched_off_hint": "Desactivada: su trabajo va a su sustituta",
  "prep.printers": "Impresoras",
  "prep.printing_rules": "Reglas de impresión",
  "prep.screens": "Pantallas de cocina",
  "prep.devices": "Dispositivos",
  "prep.none": "Ninguno",
  "prep.thresholds": "Aviso {warm} min · Atraso {overdue} min · Olvido {forgotten} min",
  "prep.shows_rest_of_order": "Mostrar el resto del pedido",
  "prep.shows_rest_of_order_hint":
    "Sus comandas y su pantalla de cocina también muestran los platos del pedido en otras estaciones.",
  "prep.name_required": "Escribe un nombre.",
  "prep.name_taken": "Este nombre ya está en uso.",
  "prep.order_invalid": "Escribe un número entero no negativo.",
  "prep.threshold_invalid": "Usa minutos enteros con aviso < atraso < olvido.",
  "prep.save": "Guardar",
  "prep.cancel": "Cancelar",
  "prep.confirm": "Confirmar",
  "prep.preview_title": "Revisar cambio de preparación",
  "prep.preview_moves": "Estos productos se prepararán en otro lugar:",
  "prep.preview_none": "Ningún producto cambia de lugar de preparación.",
  "prep.preview_product": "Producto",
  "prep.preview_from": "De",
  "prep.preview_to": "A",
  "prep.no_station": "Sin estación",
  "prep.no_replacement": "Sin sustituta",
  "prep.claim_move": "{folder} está asignada a {from}; se moverá a {to}.",
  "prep.load_error": "No se pudieron cargar las estaciones de preparación.",
  "prep.save_error": "No se pudo guardar el cambio.",
  "prep.fix_fields": "Corrige los campos marcados para continuar.",
  "prep.station_inactive": "Esta estación está desactivada. Elige una estación activa.",
  "prep.exceptions": "Excepciones",
  "prep.add_exception": "Añadir excepción",
  "prep.edit_exception": "Editar excepción",
  "prep.confirm_delete_exception": "¿Eliminar excepción?",
  "prep.delete": "Eliminar",
  "prep.actions": "Acciones",
  "prep.exception_rule": "Regla",
  "prep.reorder_exception": "Reordenar excepción",
  "prep.reordered": "{item} movida a la posición {index} de {total}",
  "prep.never_used": "Nunca se usa: una excepción anterior siempre coincide primero",
  "prep.exception_station_off": "Su estación está desactivada",
  "prep.what": "Qué",
  "prep.everything": "Todo",
  "prep.exception_from_zone": " desde {zone}",
  "prep.exception_sentence": "{what}{zone} → {target}",
  "prep.service_zone": "Zona de servicio",
  "prep.any_zone": "Cualquier zona de servicio",
  "prep.made_at": "Se prepara en",
  "prep.test_when": "Cuándo",
  "prep.test_now": "Ahora",
  "prep.test_at": "Día de la semana y hora",
  "prep.test_time": "Hora",
  "prep.test_time_required": "Elige una hora.",
  "prep.test_out_of_hours": "{station} está cerrada fuera de su horario de apertura",
  "prep.test_closed_by_hand": "{station} se ha cerrado a mano hoy",
  "prep.test_switched_off": "{station} está desactivada",
  "prep.test_fallback_step": "{reason}, por lo que su trabajo va a {destination}.",
  "prep.test_no_replacement":
    "{reason}, y no tiene sustituta, por lo que la caja pregunta al camarero dónde preparar esto.",
  "prep.test_clock_unreadable":
    "No se puede leer la zona horaria o el cambio de día del local, por lo que no se aplica el horario de apertura.",
  "prep.test_title": "¿Dónde se prepara esto?",
  "prep.test_extras_chosen": "Extras elegidos",
  "prep.test_choose_extra": "Elige un extra",
  "prep.test_remove_extra": "Quitar {name}",
  "prep.test_extras_wait": "Extras: se deciden cuando el plato tenga una estación de destino",
  "prep.test_extra_made": "{name}: se prepara en {station}, porque {reason}",
  "prep.test_extra_claim": "{station} tiene asignada la carpeta {folder}",
  "prep.test_extra_exception": "lo indica la excepción «{rule}»",
  "prep.test_extra_no_rule": "{name}: sigue al plato — ninguna excepción ni asignación lo cubre",
  "prep.test_extra_no_preparation":
    "{name}: sigue al plato — lo que lo cubre no necesita preparación, así que queda en el pedido del plato",
  "prep.test_extra_no_replacement":
    "{name}: sigue al plato — {station} está cerrada y nada puede sustituirla",
  "prep.test_extra_same_station":
    "{name}: sigue al plato — se prepara en {dishStation}, donde se prepara el plato",
  "prep.test_product": "Producto",
  "prep.test_choose_product": "Elige un producto",
  "prep.test_no_zone": "Sin zona de servicio",
  "prep.test_made_at": "Se prepara en",
  "prep.test_because": "Porque",
  "prep.test_claim": "{station} tiene asignada la carpeta {folder}",
  "prep.test_no_prep_claim": "{folder} está asignada a {target}",
  "prep.test_exception": "la excepción «{rule}»",
  "prep.test_default": "ninguna otra regla coincidió, así que va a la estación predeterminada",
  "prep.test_no_route":
    "No se puede preparar: ninguna regla coincidió y ninguna estación predeterminada está activa.",
  "prep.test_error": "No se pudo comprobar la ruta.",
  "prep.exception_condition": "Elige una carpeta o producto, una zona de servicio, o ambos",
  "prep.exception_target_required": "Elige dónde se prepara.",
  "venue.department_has_zones":
    "Mueve sus zonas de servicio activas a otro departamento antes de desactivar este departamento.",
  "venue.status": "Estado",
  "venue.active": "Activo",
  "venue.inactive": "Inactivo",
  "venue.edit": "Editar",
  "venue.delete": "Eliminar",
  "venue.save": "Guardar",
  "venue.cancel": "Cancelar",
  "venue.confirm": "Confirmar",
  "venue.confirm_remove": "Confirmar eliminación",
  "venue.no_departments": "Todavía no hay departamentos.",
  "venue.no_hours": "Todavía no hay horarios de apertura.",
  "venue.no_zones": "Todavía no hay zonas de servicio.",
  "venue.no_tills": "No hay cajas activas.",
  "venue.no_zone_menus": "Todavía no hay cartas en esta zona de servicio.",
  "venue.zone": "Zona de servicio",
  "venue.unconfigured": "Sin configurar",
  "venue.yes": "Sí",
  "venue.no": "No",
  "venue.display_order": "Orden de visualización",
  "venue.edit_department": "Editar departamento",
  "venue.edit_hours": "Editar horario",
  "venue.edit_assignment": "Editar asignación de carta",
  "venue.order_invalid": "Introduce un número entero igual o mayor que cero.",

  "nav.departments_zones": "Departamentos y zonas",
  "venue.title": "Departamentos y zonas",
  "venue.departments": "Departamentos",
  "venue.add_department": "Añadir departamento",
  "venue.name": "Nombre del departamento",
  "venue.trading_name": "Nombre comercial",
  "venue.service_style": "Estilo de servicio",
  "venue.table_tab": "Servicio de mesa",
  "venue.prepay": "Pagar antes de preparar",
  "venue.invoice_first": "Pagar y después preparar",
  "venue.ticket_then_pay": "Preparar y después pagar",
  "venue.zones": "Zonas de servicio y cartas",
  "venue.tills": "Cajas",
  "venue.starts_in": "Empieza en",
  "venue.counter_zone": "Zona del mostrador",
  "venue.department": "Departamento",
  "venue.inherit": "Usar el valor del departamento",
  "venue.save_zone": "Guardar zona",
  "venue.make_available": "Hacer disponible",
  "venue.make_default": "Establecer por defecto",
  "venue.default": "Por defecto",
  "venue.hours": "Horario de apertura",
  "venue.menus": "Cartas",
  "venue.menu_name": "Nombre de la carta",
  "venue.actions": "Acciones",
  "venue.customise_columns": "Personalizar columnas",
  "venue.customise": "Personalizar",
  "venue.restore_columns": "Restaurar valores predeterminados",
  "venue.done": "Listo",
  "venue.move_column": "Mover",
  "venue.show_column": "Mostrar",
  "venue.hide_column": "Ocultar",
  "venue.column_always_shown": "Siempre visible",
  "venue.column_last_shown": "Deja al menos una visible",
  "venue.column_position": "{position} de {total}",
  "venue.weekday": "Día",
  "venue.opens": "Abre",
  "venue.closes": "Cierra",
  "venue.add_hours": "Añadir horario",
  "venue.required": "Completa todos los campos obligatorios.",
  "venue.fix_fields": "Corrige los campos marcados para continuar.",
  "venue.field_required": "Este campo es obligatorio.",
  "venue.field_refused": "No se ha aceptado este valor. Cámbialo y vuelve a guardar.",
  "prep.time_required": "Indica las horas de apertura y cierre.",
  "venue.time_distinct": "Las horas de apertura y cierre deben ser distintas.",
  "venue.day.0": "Domingo",
  "venue.day.1": "Lunes",
  "venue.day.2": "Martes",
  "venue.day.3": "Miércoles",
  "venue.day.4": "Jueves",
  "venue.day.5": "Viernes",
  "venue.day.6": "Sábado",
  "venue.load_error": "No se pudo cargar la configuración del local.",
  "venue.save_error": "No se pudo guardar el cambio.",
  "venue.readiness": "Preparado para el servicio",
  "venue.readiness.ok": "Todas las zonas activas están preparadas para aceptar pedidos.",
  "venue.readiness.department_missing": "Crea un departamento activo antes del servicio.",
  "venue.readiness.default_station_missing":
    "Ninguna estación de preparación predeterminada está activa. Los artículos que ninguna regla envía a una estación no se pueden enviar.",
  "venue.readiness.zone_department_missing": "necesita un departamento activo.",
  "venue.readiness.zone_menu_missing": "necesita una carta predeterminada.",
  "venue.readiness.menu_empty": "no tiene productos para",
  "venue.readiness.zone_menu_unpublished": "necesita una carta activa y publicada.",
  "venue.deactivate_department": "Desactivar departamento",
  "venue.kitchen_changes": "Cambios tras el envío",
  "venue.edit_sent_lines": "Permitir cambios en los artículos ya enviados a cocina",
  "venue.edit_sent_lines_hint":
    "Si está desactivado, el personal no puede cambiar ni retirar un artículo que ya tiene la cocina; tiene que cancelarlo.",
  "venue.kitchen_ticket_grouping": "Platos iguales en una comanda de cocina",
  "venue.kitchen_ticket_grouping.combined": "Una línea: 3 x Hamburguesa",
  "venue.kitchen_ticket_grouping.separate": "Una por plato: 1 x Hamburguesa, tres veces",
  "venue.kitchen_ticket_grouping_hint":
    "Se aplica a las comandas de cocina nuevas y a las reimpresiones.",
  "venue.release_reminder": "Aviso para marchar el siguiente grupo",
  "venue.release_reminder.off": "Desactivado",
  "venue.release_reminder.minutes": "{n} minutos",
  "venue.release_reminder_hint":
    "Se cuenta desde que cada grupo marchado antes del siguiente grupo en espera se ha marcado como servido. El personal puede posponerlo desde la mesa.",
  "venue.print_held_work": "Imprimir por adelantado los grupos en espera",
  "venue.print_held_work_hint":
    "Un grupo en espera se imprime en el momento en una comanda de cocina marcada HOLD. Añadir, mover, quitar o cambiar sus platos imprime después una corrección HOLD, y al marcharlo se imprime su comanda marcada FIRE. Un grupo que ya estaba en espera antes de activarlo se imprime al marcharlo, como hasta ahora. Un grupo ya impreso como HOLD se sigue marchando marcado FIRE aunque se desactive.",
  "venue.clearing_workflow": "Por recoger",
  "venue.clearing_workflow_hint":
    "Si está activado, una mesa que un grupo deja —al Cerrar mesa, al cambiarse a otra mesa o al unirse a otro grupo— aparece Por recoger hasta que alguien la marca como recogida.",
  "venue.combobox_search": "Buscar",
  "venue.combobox_no_results": "Sin resultados",
  "venue.decrease": "Reducir {label}",
  "venue.increase": "Aumentar {label}",
};

export const VENUE_SERVICE_STRINGS = { en, es };
registerCatalogue(VENUE_SERVICE_STRINGS);
export const t = makeT<keyof typeof en>();
