import { makeT, registerCatalogue } from "@waitron/dashboard-kit";

const en = {
  "nav.venue_operations": "Venue operations",
  "venue.title": "Venue operations",
  "venue.departments": "Departments",
  "venue.add_department": "Add department",
  "venue.name": "Department name",
  "venue.trading_name": "Trading name",
  "venue.service_style": "Service style",
  "venue.table_tab": "Table service",
  "venue.prepay": "Pay before preparation",
  "venue.invoice_first": "Pay then prepare",
  "venue.ticket_then_pay": "Prepare then pay",
  "venue.zones": "Service zones and menus",
  "venue.department": "Department",
  "venue.inherit": "Use department default",
  "venue.save_zone": "Save zone",
  "venue.make_available": "Make available",
  "venue.make_default": "Make default",
  "venue.default": "Default",
  "venue.hours": "Opening hours",
  "venue.menus": "Menus",
  "venue.add_menu": "Add menu",
  "venue.menu_name": "Menu name",
  "venue.section": "Section",
  "venue.product": "Product",
  "venue.price": "Price",
  "venue.add_offer": "Add product to menu",
  "venue.no_offers": "No products on this menu.",
  "venue.weekday": "Day",
  "venue.opens": "Opens",
  "venue.closes": "Closes",
  "venue.add_hours": "Add hours",
  "venue.routing": "Preparation routing",
  "venue.category": "Product category",
  "venue.product_or_category": "Product or category",
  "venue.all_zones": "All service zones",
  "venue.station": "Preparation station",
  "venue.no_preparation": "No preparation",
  "venue.add_route": "Add route",
  "venue.required": "Fill in every required field.",
  "venue.load_error": "The venue configuration could not be loaded.",
  "venue.save_error": "The change could not be saved.",
  "venue.empty": "No departments have been configured.",
  "venue.readiness": "Ready for service",
  "venue.readiness.ok": "Every active service zone is ready to take orders.",
  "venue.readiness.department_missing": "Create an active department before service.",
  "venue.readiness.zone_department_missing": "needs an active department.",
  "venue.readiness.zone_menu_missing": "needs a default menu.",
  "venue.readiness.menu_empty": "has no products for",
  "venue.readiness.route_missing": "needs a preparation route in",
  "venue.deactivate_department": "Deactivate department",
} as const;

const es: Record<keyof typeof en, string> = {
  "nav.venue_operations": "Operaciones del local",
  "venue.title": "Operaciones del local",
  "venue.departments": "Departamentos",
  "venue.add_department": "Añadir departamento",
  "venue.name": "Nombre del departamento",
  "venue.trading_name": "Nombre comercial",
  "venue.service_style": "Estilo de servicio",
  "venue.table_tab": "Servicio de mesa",
  "venue.prepay": "Pagar antes de preparar",
  "venue.invoice_first": "Pagar y después preparar",
  "venue.ticket_then_pay": "Preparar y después pagar",
  "venue.zones": "Zonas de servicio y cartas",
  "venue.department": "Departamento",
  "venue.inherit": "Usar el valor del departamento",
  "venue.save_zone": "Guardar zona",
  "venue.make_available": "Hacer disponible",
  "venue.make_default": "Establecer por defecto",
  "venue.default": "Por defecto",
  "venue.hours": "Horario de apertura",
  "venue.menus": "Cartas",
  "venue.add_menu": "Añadir carta",
  "venue.menu_name": "Nombre de la carta",
  "venue.section": "Sección",
  "venue.product": "Producto",
  "venue.price": "Precio",
  "venue.add_offer": "Añadir producto a la carta",
  "venue.no_offers": "Esta carta no tiene productos.",
  "venue.weekday": "Día",
  "venue.opens": "Abre",
  "venue.closes": "Cierra",
  "venue.add_hours": "Añadir horario",
  "venue.routing": "Rutas de preparación",
  "venue.category": "Categoría de producto",
  "venue.product_or_category": "Producto o categoría",
  "venue.all_zones": "Todas las zonas de servicio",
  "venue.station": "Estación de preparación",
  "venue.no_preparation": "Sin preparación",
  "venue.add_route": "Añadir ruta",
  "venue.required": "Completa todos los campos obligatorios.",
  "venue.load_error": "No se pudo cargar la configuración del local.",
  "venue.save_error": "No se pudo guardar el cambio.",
  "venue.empty": "No hay departamentos configurados.",
  "venue.readiness": "Preparado para el servicio",
  "venue.readiness.ok": "Todas las zonas activas están preparadas para aceptar pedidos.",
  "venue.readiness.department_missing": "Crea un departamento activo antes del servicio.",
  "venue.readiness.zone_department_missing": "necesita un departamento activo.",
  "venue.readiness.zone_menu_missing": "necesita una carta predeterminada.",
  "venue.readiness.menu_empty": "no tiene productos para",
  "venue.readiness.route_missing": "necesita una ruta de preparación en",
  "venue.deactivate_department": "Desactivar departamento",
};

export const VENUE_SERVICE_STRINGS = { en, es };
registerCatalogue(VENUE_SERVICE_STRINGS);
export const t = makeT<keyof typeof en>();
