// Idempotent local-dev bootstrap for SETUP MODE: migrate a local Postgres and write a venue-less
// `apps/server/.env`, so `pnpm dev` boots the server UNPROVISIONED and the slice-1b setup surface
// (`/setup-api/status` + the placeholder page) is exercisable on a laptop. A trimmed `dev-setup.ts`
// that STOPS after migrating — it never provisions a venue, so it mints no fiscal chain and writes
// none of the five `WAITRON_TILL_*_ID` or the `WAITRON_CREDENTIALS_KEY` a trading box needs. Setup
// mode needs neither: `boot.ts`'s `config.till === undefined` branch loads no key ring and mounts no
// trading routes (see `boot.test.ts`'s setup-mode boot, landed Task 3).
//
// FISCAL NOTE (CLAUDE.md §5): a venue-bearing database is NOT a setup-mode target — provisioning a
// second venue would start a second SIF and a second hash chain. So this REFUSES to run against a
// database that already holds any venue (it never deletes data itself), directing the operator to
// wipe the throwaway dev volume and re-run. The only setup-mode target is an UNPROVISIONED database:
// a fresh/wiped volume, or one this script migrated but never provisioned. `pnpm dev:setup` /
// `pnpm dev:reset` provision a venue, so a box that has run either is a TRADING target, not this one.
//
// Run from the repo root via `pnpm dev:onboard` (which brings the container up first); this script
// only polls the connection, migrates, and writes the `.env`.
import { realpathSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { applyMigrations, manifestSets, migrationOptionsFor } from "@waitron/migrations";
// Reuse dev-setup's building blocks rather than re-implement them: the connection poll, the venue
// probe, the keyed-`.env` renderer and the options shape are identical needs, and one copy keeps the
// two scripts' behaviour from drifting.
import {
  DEV_DATABASE_URL,
  inspectVenues,
  renderEnvFileLines,
  waitForPostgres,
} from "./dev-setup.js";
import type { DevSetupOptions } from "./dev-setup.js";

/**
 * The env contract a SETUP-MODE box boots against — a deliberate SUBSET of `dev-setup`'s `DevEnv`.
 * DATABASE_URL + environment + port and nothing else: `boot.ts`'s setup branch (`config.till ===
 * undefined`) mounts only `/health` + the setup surface, so it reads no `WAITRON_TILL_*_ID` (their
 * absence is what SELECTS setup mode — `tryLoadTillConfig` returns undefined) and no
 * `WAITRON_CREDENTIALS_KEY` (no key ring is loaded on the setup path).
 */
export interface SetupEnv {
  DATABASE_URL: string;
  WAITRON_ENV: string;
  WAITRON_HTTP_PORT: string;
}

/** Ordered so `renderSetupEnvFile` emits a stable, reviewable `.env`. */
const SETUP_ENV_KEYS: readonly (keyof SetupEnv)[] = [
  "DATABASE_URL",
  "WAITRON_ENV",
  "WAITRON_HTTP_PORT",
];

/** The `.env` text: a generated-by header, then one `KEY=value` line per setup-contract key. Pure. */
export function renderSetupEnvFile(env: SetupEnv): string {
  const header =
    "# Generated by `pnpm dev:onboard` (setup mode — no venue bound) — do not edit by hand.";
  return renderEnvFileLines(header, SETUP_ENV_KEYS, env);
}

/**
 * The options a setup-mode bootstrap takes — structurally identical to `dev-setup`'s
 * `DevSetupOptions` (databaseUrl + envPath + optional log), so it is an ALIAS rather than a second
 * declaration the two could silently drift apart on.
 */
export type DevOnboardOptions = DevSetupOptions;

export interface DevOnboardResult {
  env: SetupEnv;
}

/**
 * Migrate a local Postgres and write a venue-less `.env`, so the server boots in SETUP MODE. Unlike
 * `dev-setup`, it provisions NOTHING (CLAUDE.md §5 — a venue is a SIF and a hash chain). Two cases:
 *
 *  - the database holds no venue (a fresh/wiped volume, or one migrated but never provisioned) →
 *    migrate and write the setup `.env`;
 *  - the database ALREADY holds a venue → REFUSE. A provisioned database is a trading target, not a
 *    setup one, and this script must never turn a live chain's box into a setup box. The operator
 *    wipes the throwaway dev volume and re-runs to start over.
 */
export async function devOnboard(opts: DevOnboardOptions): Promise<DevOnboardResult> {
  const { databaseUrl, envPath, log = () => {} } = opts;

  await waitForPostgres(databaseUrl, log);

  // Refuse a venue-bearing database BEFORE migrating: setup mode is for an UNPROVISIONED box.
  // `expectedTenantId` is `null` — there is no `.env` venue to match, so only `hasAny` matters here.
  // An unmigrated database (no `tenants` table) reads as "no venue" (`inspectVenues` maps
  // `42P01 undefined_table` → both-false), so a fresh volume falls straight through to migrate.
  const { hasAny } = await inspectVenues(databaseUrl, null);
  if (hasAny) {
    throw new Error(
      "dev-onboard: the database already holds a venue, so it is not a setup-mode target — setup " +
        "mode is for an UNPROVISIONED box. Refusing to touch a database that holds a fiscal chain " +
        "(a `dev:setup`/`dev:reset` box is a TRADING target). To exercise setup mode, wipe the " +
        "throwaway dev volume and re-run: " +
        "`docker compose down -v && pnpm dev:onboard`.",
    );
  }

  // Migrate the full manifest from source — the exact call `dev-setup` makes (dev-setup.ts's
  // `applyMigrations(databaseUrl, migrationOptionsFor(manifestSets(), null))`): the same sets the
  // server migrates at boot, `null` being the from-source root resolved to each package's own
  // `drizzle` dir. Then STOP — no venue is provisioned.
  log("dev-onboard: migrating…");
  await applyMigrations(databaseUrl, migrationOptionsFor(manifestSets(), null));

  const env: SetupEnv = {
    DATABASE_URL: databaseUrl,
    WAITRON_ENV: "preproduction",
    WAITRON_HTTP_PORT: "8080",
  };
  writeFileSync(envPath, renderSetupEnvFile(env));
  log(`dev-onboard: wrote ${envPath} (setup mode — no venue bound)`);
  return { env };
}

/** The CLI entrypoint: resolve `apps/server/.env`, run `devOnboard`, print a human summary. */
async function main(): Promise<void> {
  const envPath = fileURLToPath(new URL("../.env", import.meta.url));
  const databaseUrl =
    process.env.DATABASE_URL !== undefined && process.env.DATABASE_URL !== ""
      ? process.env.DATABASE_URL
      : DEV_DATABASE_URL;

  await devOnboard({
    databaseUrl,
    envPath,
    log: (line) => void console.log(line),
  });

  console.log("");
  console.log("dev-onboard: migrated an UNPROVISIONED database — the box will boot in SETUP MODE.");
  console.log("");
  console.log(
    "  server     https://localhost:8080   (self-signed cert — browser warning is expected)",
  );
  console.log("  status     https://localhost:8080/setup-api/status   (provisioned: false)");
  console.log("");
  console.log(
    "Next: `pnpm dev` (or `pnpm --filter @waitron/server dev`) to boot in setup mode. First",
  );
  console.log(
    "setup boot mints a self-signed CA + leaf into WAITRON_STATE_DIR (default apps/server/src/state,",
  );
  console.log("gitignored) and serves HTTPS from it. Verify manually with:");
  console.log("");
  console.log("  curl -sk https://127.0.0.1:8080/setup-api/status");
  console.log('  curl -sk -o /dev/null -w "%{http_code}\\n" https://127.0.0.1:8080/');
}

// Run only when invoked directly (`tsx scripts/dev-onboard.ts`), never when imported by a test — the
// same guard `dev-setup.ts` uses so importing this module for a unit test never spins a container.
if (
  process.argv[1] !== undefined &&
  realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))
) {
  main().catch((error: unknown) => {
    console.error("dev-onboard: failed");
    console.error(error);
    process.exit(1);
  });
}
