// Idempotent local-dev bootstrap for SETUP MODE: migrate a local venue DIRECTORY and write a
// venue-less `apps/server/.env`, so `pnpm dev` boots the server UNPROVISIONED and the slice-1b setup
// surface (`/setup-api/status` + the placeholder page) is exercisable on a laptop. A trimmed
// `dev-setup.ts` that STOPS after migrating — it never provisions a venue, so it mints no fiscal
// chain and writes none of the four `WAITRON_TILL_*_ID`. Setup boot creates and loads its own key
// ring from the persistent state directory so it can stage configuration and seal the first venue's
// credentials.
//
// FISCAL NOTE (CLAUDE.md §5): a venue-bearing directory is NOT a setup-mode target — provisioning a
// second venue would start a second SIF and a second hash chain. So this REFUSES to run against a
// venue directory that already holds any venue (it never deletes data itself), directing the
// operator to remove the throwaway dev venue and re-run. The only setup-mode target is an
// UNPROVISIONED directory: a fresh/removed one, or one this script migrated but never provisioned.
// `pnpm dev:setup` / `pnpm dev:reset` provision a venue, so a box that has run either is a TRADING
// target, not this one.
//
// Run from the repo root via `pnpm dev:onboard`; it opens the venue directory, migrates it, and
// writes the `.env`.
import { realpathSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { applyMigrations, manifestSets, migrationOptionsFor } from "@waitron/migrations";
import { resolveConfigDir } from "../src/config.js";
// Reuse dev-setup's building blocks rather than re-implement them: the venue probe, the
// venue-directory default, the keyed-`.env` renderer and the options shape are identical needs, and
// one copy keeps the two scripts' behaviour from drifting.
import {
  defaultDevVenueDir,
  inspectVenues,
  renderEnvFileLines,
  resetVenueDir,
} from "./dev-setup.js";
import type { DevSetupOptions } from "./dev-setup.js";

/**
 * The env contract a SETUP-MODE box boots against — a deliberate SUBSET of `dev-setup`'s `DevEnv`.
 * The venue directory + environment + port and nothing else: `boot.ts`'s setup branch (`config.till ===
 * undefined`) mounts only `/health` + the setup surface, so it reads no `WAITRON_TILL_*_ID` (their
 * absence is what SELECTS setup mode — `tryLoadTillConfig` returns undefined). The key ring is
 * generated in the persistent state directory by setup boot, outside this environment file.
 */
export interface SetupEnv {
  WAITRON_VENUE_DIR: string;
  WAITRON_ENV: string;
  WAITRON_HTTP_PORT: string;
}

/** Ordered so `renderSetupEnvFile` emits a stable, reviewable `.env`. */
const SETUP_ENV_KEYS: readonly (keyof SetupEnv)[] = [
  "WAITRON_VENUE_DIR",
  "WAITRON_ENV",
  "WAITRON_HTTP_PORT",
];

/** The `.env` text: a generated-by header, then one `KEY=value` line per setup-contract key. Pure. */
export function renderSetupEnvFile(env: SetupEnv): string {
  const header =
    "# Generated by `pnpm dev:onboard` (setup mode — no venue bound) — do not edit by hand.";
  return renderEnvFileLines(header, SETUP_ENV_KEYS, env);
}

/**
 * The options a setup-mode bootstrap takes — `dev-setup`'s `DevSetupOptions` MINUS `stateDir`, so the
 * shared fields (venueDir + envPath + optional log) cannot silently drift while the field only the
 * provisioning path needs is dropped. A setup-mode box provisions no venue and never resolves the fiscal
 * slot (boot's `config.till === undefined` branch), so it writes no `modules.json` and needs no state dir.
 */
export type DevOnboardOptions = Omit<DevSetupOptions, "stateDir">;

export interface DevOnboardResult {
  env: SetupEnv;
}

/**
 * Migrate a local venue directory and write a venue-less `.env`, so the server boots in SETUP MODE. Unlike
 * `dev-setup`, it provisions NOTHING (CLAUDE.md §5 — a venue is a SIF and a hash chain). Two cases:
 *
 *  - the database holds no venue (a fresh/wiped volume, or one migrated but never provisioned) →
 *    migrate and write the setup `.env`;
 *  - the database ALREADY holds a venue → REFUSE. A provisioned database is a trading target, not a
 *    setup one, and this script must never turn a live chain's box into a setup box. The operator
 *    wipes the throwaway dev volume and re-runs to start over.
 */
export async function devOnboard(opts: DevOnboardOptions): Promise<DevOnboardResult> {
  const { venueDir, envPath, log = () => {} } = opts;

  // Refuse a venue-bearing directory BEFORE migrating: setup mode is for an UNPROVISIONED box.
  // The expected till id is `null` — there is no `.env` venue to match, so only `hasAny` matters here.
  // An unmigrated directory (no `tenants` table) reads as "no venue", and a VIRGIN one opens rather
  // than failing, so a fresh laptop falls straight through to migrate.
  const { hasAny } = await inspectVenues(venueDir, null);
  if (hasAny) {
    throw new Error(
      "dev-onboard: the venue directory already holds a venue, so it is not a setup-mode target — " +
        "setup mode is for an UNPROVISIONED box. Refusing to touch a venue that holds a fiscal chain " +
        "(a `dev:setup`/`dev:reset` box is a TRADING target). To exercise setup mode, remove the " +
        "throwaway dev venue and re-run: `pnpm dev:reset:onboard`.",
    );
  }

  // Migrate the full manifest into the venue directory. Then STOP — no venue is provisioned.
  log("dev-onboard: migrating…");
  await applyMigrations(venueDir, migrationOptionsFor(manifestSets(), null));

  // `venueDir` is also what `POST /setup-api/provision` runs `applyVenue` over once the box boots:
  // the server opens this same directory, so the setup surface and this script address one venue.
  const env: SetupEnv = {
    WAITRON_VENUE_DIR: venueDir,
    WAITRON_ENV: "dev",
    WAITRON_HTTP_PORT: "8080",
  };
  writeFileSync(envPath, renderSetupEnvFile(env));
  log(`dev-onboard: wrote ${envPath} (setup mode — no venue bound)`);
  return { env };
}

/**
 * The CLI entrypoint: resolve `apps/server/.env` and the venue directory, run `devOnboard`, print a
 * human summary. `--reset` removes the venue directory first, the same flag `dev-setup` takes.
 */
async function main(): Promise<void> {
  const envPath = fileURLToPath(new URL("../.env", import.meta.url));

  // The venue dir resolved exactly as `config.ts` and `dev-setup` resolve it, off the same state
  // dir, so this script migrates the directory `pnpm dev` then opens.
  const { DEFAULT_STATE_ROOT } = await import("../src/boot.js");
  const stateDir = resolveConfigDir(process.env.WAITRON_STATE_DIR, DEFAULT_STATE_ROOT);
  const venueDir = resolveConfigDir(process.env.WAITRON_VENUE_DIR, defaultDevVenueDir(stateDir));

  if (process.argv.includes("--reset")) {
    resetVenueDir(venueDir);
    console.log(`dev-onboard: removed ${venueDir}`);
  }

  await devOnboard({
    venueDir,
    envPath,
    log: (line) => void console.log(line),
  });

  console.log("");
  console.log("dev-onboard: migrated an UNPROVISIONED database — the box will boot in SETUP MODE.");
  console.log("");
  console.log(
    "  wizard     http://localhost:5192   (the setup UI — apps/setup Vite dev server, open this)",
  );
  console.log(
    "  server     https://localhost:8080   (self-signed cert — browser warning is expected)",
  );
  console.log("  status     https://localhost:8080/setup-api/status   (provisioned: false)");
  console.log("");
  console.log(
    "Next: `pnpm dev` (or `pnpm --filter @waitron/server dev`) to boot in setup mode. First",
  );
  console.log(
    "setup boot mints a self-signed CA + leaf into WAITRON_STATE_DIR (default apps/server/src/state,",
  );
  console.log(
    "gitignored) and serves HTTPS from it. Development does not advertise `waitron.local`. Verify with:",
  );
  console.log("");
  console.log("  curl -sk https://127.0.0.1:8080/setup-api/status");
  console.log('  curl -sk -o /dev/null -w "%{http_code}\\n" https://127.0.0.1:8080/');
  console.log(
    '  curl -sk https://127.0.0.1:8080/setup-api/discovery         # {"hostname":"waitron.local","addresses":[...],...}',
  );
  console.log(
    "  curl -sk https://127.0.0.1:8080/setup-api/ca.crt -o /tmp/waitron-ca.crt   # the box CA",
  );
  console.log(
    '  curl -sk -o /dev/null -w "%{http_code}\\n" https://127.0.0.1:8080/setup/trust   # 200 (trust page)',
  );
}

// Run only when invoked directly (`tsx scripts/dev-onboard.ts`), never when imported by a test — the
// same guard `dev-setup.ts` uses so importing this module for a unit test never spins a container.
if (
  process.argv[1] !== undefined &&
  realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))
) {
  main().catch((error: unknown) => {
    console.error("dev-onboard: failed");
    console.error(error);
    process.exit(1);
  });
}
