// Local-dev bootstrap for setup mode: migrate a local venue directory and write a venue-less
// `apps/server/.env`, so `pnpm dev` boots the server unprovisioned. Run from the repo root via
// `pnpm dev:onboard`.
//
// It refuses a directory that already holds a venue: provisioning a second one would start a second
// SIF and a second hash chain (CLAUDE.md §5). It never deletes data itself.
import { realpathSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { applyMigrations, manifestSets, migrationOptionsFor } from "@waitron/migrations";
import { resolveConfigDir } from "../src/config.js";
import {
  defaultDevVenueDir,
  inspectVenues,
  renderEnvFileLines,
  resetVenueDir,
} from "./dev-setup.js";
import type { DevSetupOptions } from "./dev-setup.js";

/**
 * No `WAITRON_TILL_*_ID`: their absence is what selects setup mode (`tryLoadTillConfig` returns
 * undefined). Setup boot generates its own key ring in the state directory.
 */
export interface SetupEnv {
  WAITRON_VENUE_DIR: string;
  WAITRON_ENV: string;
  WAITRON_HTTP_PORT: string;
}

const SETUP_ENV_KEYS: readonly (keyof SetupEnv)[] = [
  "WAITRON_VENUE_DIR",
  "WAITRON_ENV",
  "WAITRON_HTTP_PORT",
];

export function renderSetupEnvFile(env: SetupEnv): string {
  const header =
    "# Generated by `pnpm dev:onboard` (setup mode — no venue bound) — do not edit by hand.";
  return renderEnvFileLines(header, SETUP_ENV_KEYS, env);
}

/** No `stateDir`: a setup-mode box never resolves the fiscal slot, so no `modules.json` is written. */
export type DevOnboardOptions = Omit<DevSetupOptions, "stateDir">;

export interface DevOnboardResult {
  env: SetupEnv;
}

/** Provisions nothing, and refuses a directory that already holds a venue (CLAUDE.md §5). */
export async function devOnboard(opts: DevOnboardOptions): Promise<DevOnboardResult> {
  const { venueDir, envPath, log = () => {} } = opts;

  const { hasAny } = await inspectVenues(venueDir, null);
  if (hasAny) {
    throw new Error(
      "dev-onboard: the venue directory already holds a venue, so it is not a setup-mode target — " +
        "setup mode is for an UNPROVISIONED box. Refusing to touch a venue that holds a fiscal chain " +
        "(a `dev:setup`/`dev:reset` box is a TRADING target). To exercise setup mode, remove the " +
        "throwaway dev venue and re-run: `pnpm dev:reset:onboard`.",
    );
  }

  log("dev-onboard: migrating…");
  await applyMigrations(venueDir, migrationOptionsFor(manifestSets(), null));

  const env: SetupEnv = {
    WAITRON_VENUE_DIR: venueDir,
    WAITRON_ENV: "dev",
    WAITRON_HTTP_PORT: "8080",
  };
  writeFileSync(envPath, renderSetupEnvFile(env));
  log(`dev-onboard: wrote ${envPath} (setup mode — no venue bound)`);
  return { env };
}

/** `--reset` removes the venue directory first. */
async function main(): Promise<void> {
  const envPath = fileURLToPath(new URL("../.env", import.meta.url));

  // Resolved exactly as `config.ts` does, so this migrates the directory `pnpm dev` opens.
  const { DEFAULT_STATE_ROOT } = await import("../src/boot.js");
  const stateDir = resolveConfigDir(process.env.WAITRON_STATE_DIR, DEFAULT_STATE_ROOT);
  const venueDir = resolveConfigDir(process.env.WAITRON_VENUE_DIR, defaultDevVenueDir(stateDir));

  if (process.argv.includes("--reset")) {
    resetVenueDir(venueDir);
    console.log(`dev-onboard: removed ${venueDir}`);
  }

  await devOnboard({
    venueDir,
    envPath,
    log: (line) => void console.log(line),
  });

  console.log("");
  console.log("dev-onboard: migrated an UNPROVISIONED database — the box will boot in SETUP MODE.");
  console.log("");
  console.log(
    "  wizard     http://localhost:5192   (the setup UI — apps/setup Vite dev server, open this)",
  );
  console.log(
    "  server     https://localhost:8080   (self-signed cert — browser warning is expected)",
  );
  console.log("  status     https://localhost:8080/setup-api/status   (provisioned: false)");
  console.log("");
  console.log(
    "Next: `pnpm dev` (or `pnpm --filter @waitron/server dev`) to boot in setup mode. First",
  );
  console.log(
    "setup boot mints a self-signed CA + leaf into WAITRON_STATE_DIR (default apps/server/src/state,",
  );
  console.log(
    "gitignored) and serves HTTPS from it. Development does not advertise `waitron.local`. Verify with:",
  );
  console.log("");
  console.log("  curl -sk https://127.0.0.1:8080/setup-api/status");
  console.log('  curl -sk -o /dev/null -w "%{http_code}\\n" https://127.0.0.1:8080/');
  console.log(
    '  curl -sk https://127.0.0.1:8080/setup-api/discovery         # {"hostname":"waitron.local","addresses":[...],...}',
  );
  console.log(
    "  curl -sk https://127.0.0.1:8080/setup-api/ca.crt -o /tmp/waitron-ca.crt   # the box CA",
  );
  console.log(
    '  curl -sk -o /dev/null -w "%{http_code}\\n" https://127.0.0.1:8080/setup/trust   # 200 (trust page)',
  );
}

// Run only when invoked directly, never when imported by a test.
if (
  process.argv[1] !== undefined &&
  realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))
) {
  main().catch((error: unknown) => {
    console.error("dev-onboard: failed");
    console.error(error);
    process.exit(1);
  });
}
