// Idempotent local-dev bootstrap: provision ONE preproduction venue into a local Postgres and
// persist its identity to `apps/server/.env`, so `pnpm dev` boots the server against a real,
// migrated, seeded venue. A trimmed `till-demo.ts` that stops after provisioning + seeding and
// writes the ids down, plus a reuse guard that never re-provisions a live dev database.
//
// FISCAL NOTE (CLAUDE.md §5): re-registering a till starts a NEW hash chain and mints a fresh
// installation number. So this REUSES an already-provisioned venue (an existing `.env` naming a
// tenant the database still holds) and REFUSES to provision when the database already holds a venue
// this `.env` cannot account for — it never mints a second one into a live database. The only
// sanctioned "start over" is `pnpm dev:reset`, which wipes the Docker volume (throwaway
// preproduction data); this script never deletes data itself.
//
// Run from the repo root via `pnpm dev:setup` (which brings the container up first); this script
// only polls the connection and provisions. Never against a production database — it creates a
// tenant and chains real fiscal records under `preproduction`.
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { setTimeout as delay } from "node:timers/promises";
import pg from "pg";
import { sql } from "drizzle-orm";
import { asAppUser, createPostgresDb, withTenant, type Database } from "@waitron/db";
import { hashPassword, hashPin } from "@waitron/identity";
import { applyMigrations, manifestSets, migrationOptionsFor } from "@waitron/migrations";
import { applyVenue, planVenue } from "@waitron/provisioning";
import {
  assignCatalogueToLocation,
  createCatalogue,
  createCategory,
  createProduct,
} from "@waitron/catalogue";
import { tenantId as brandTenantId } from "@waitron/shared";

/** The container superuser + default database every demo uses — one place so the scripts agree. */
export const DEV_DATABASE_URL = "postgres://postgres:pg@localhost:5432/postgres";

/** The seeded cashier's PIN (login) and the provisioned admin's PIN — printed for the operator. */
export const CASHIER_PIN = "5555";
export const ADMIN_PIN = "1234";
/** The provisioned admin's dashboard password — mirrors `till-demo.ts`. */
const ADMIN_PASSWORD = "dashPass123";

const LOCALE = "es-ES";

/** The exact env contract `apps/server` boots against (config.ts + till-config.ts), in write order. */
export interface DevEnv {
  DATABASE_URL: string;
  WAITRON_ENV: string;
  WAITRON_HTTP_PORT: string;
  WAITRON_CREDENTIALS_KEY: string;
  WAITRON_CREDENTIALS_KEY_VERSION: string;
  WAITRON_TILL_TENANT_ID: string;
  WAITRON_TILL_TILL_ID: string;
  WAITRON_TILL_NODE_ID: string;
  WAITRON_TILL_SERIES_ID: string;
  WAITRON_TILL_LOCATION_ID: string;
}

/** Ordered so `renderEnvFile` emits a stable, reviewable `.env`. */
const ENV_KEYS: readonly (keyof DevEnv)[] = [
  "DATABASE_URL",
  "WAITRON_ENV",
  "WAITRON_HTTP_PORT",
  "WAITRON_CREDENTIALS_KEY",
  "WAITRON_CREDENTIALS_KEY_VERSION",
  "WAITRON_TILL_TENANT_ID",
  "WAITRON_TILL_TILL_ID",
  "WAITRON_TILL_NODE_ID",
  "WAITRON_TILL_SERIES_ID",
  "WAITRON_TILL_LOCATION_ID",
];

/** The `.env` text: a generated-by header, then one `KEY=value` line per contract key. Pure. */
export function renderEnvFile(env: DevEnv): string {
  const header =
    "# Generated by `pnpm dev:setup` — do not edit by hand. Regenerate: `pnpm dev:reset`.";
  const lines = ENV_KEYS.map((key) => `${key}=${env[key]}`);
  return [header, ...lines].join("\n") + "\n";
}

/**
 * Parse a `.env`'s `KEY=value` lines, skipping blank and `#` comment lines and splitting on the
 * FIRST `=` (a value may itself contain `=`). Node's `--env-file` owns the runtime parse; this is
 * only for reading our OWN generated file back (the reuse guard, and the round-trip test). Pure.
 */
export function parseEnvFile(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    out[line.slice(0, eq)] = line.slice(eq + 1);
  }
  return out;
}

export interface DevSetupOptions {
  /** The database to provision into and to write as `DATABASE_URL`. */
  databaseUrl: string;
  /** Where to read/write the `.env`. */
  envPath: string;
  log?: (line: string) => void;
}

export interface DevSetupResult {
  /** True when an already-provisioned venue was reused (no new fiscal chain). */
  reused: boolean;
  env: DevEnv;
}

/** True once every env-contract key is present and non-empty in a parsed `.env`. */
function isCompleteDevEnv(rec: Record<string, string>): rec is Record<string, string> & DevEnv {
  return ENV_KEYS.every((key) => {
    const value = rec[key];
    return value !== undefined && value !== "";
  });
}

/** Poll until Postgres accepts a connection. The root `dev:setup`/`dev:reset` scripts already pass
 * `docker compose up -d --wait db` (so Docker blocks on the healthcheck), but a direct
 * `pnpm --filter @waitron/server dev:setup` skips that gate, so this is the readiness net for the
 * standalone path — one immediate connect on the warm path. */
export async function waitForPostgres(uri: string, log: (line: string) => void): Promise<void> {
  const attempts = 60;
  const delayMs = 1000;
  for (let i = 1; i <= attempts; i++) {
    const client = new pg.Client({ connectionString: uri });
    try {
      await client.connect();
      await client.query("select 1");
      return;
    } catch (error) {
      if (i === attempts) {
        throw new Error(
          `dev-setup: Postgres at the configured DATABASE_URL did not accept connections after ${attempts} attempts — is \`docker compose up -d db\` running?`,
          { cause: error },
        );
      }
      if (i === 1) log("dev-setup: waiting for Postgres…");
      await delay(delayMs);
    } finally {
      await client.end().catch(() => {});
    }
  }
}

/**
 * Two facts about a database's venues, read in one connection: whether it holds the SPECIFIC tenant
 * the `.env` names (`hasExpected` — reuse this venue), and whether it holds ANY tenant at all
 * (`hasAny` — refuse to provision a second one). `expectedTenantId` is `null` when there is no usable
 * `.env` to match, in which case `hasExpected` is trivially false.
 *
 * A missing `tenants` table (an unmigrated database — e.g. a freshly wiped volume) is "no venue at
 * all", so `42P01 undefined_table` returns both-false and the caller provisions fresh. Any OTHER
 * failure (a permission error, a malformed id → `22P02`, a connection blip after `waitForPostgres`
 * already succeeded) must NOT be read as "no venue": that would route a database already holding a
 * chain into a spurious re-provision — a second SIF, a second hash chain (CLAUDE.md §5). Those fail
 * loud.
 */
export async function inspectVenues(
  uri: string,
  expectedTenantId: string | null,
): Promise<{ hasExpected: boolean; hasAny: boolean }> {
  const client = new pg.Client({ connectionString: uri });
  try {
    await client.connect();
    const { rows } = await client.query<{ has_expected: boolean; has_any: boolean }>(
      "select exists(select 1 from tenants where id = $1) as has_expected, exists(select 1 from tenants) as has_any",
      [expectedTenantId],
    );
    return { hasExpected: rows[0]?.has_expected ?? false, hasAny: rows[0]?.has_any ?? false };
  } catch (error) {
    if (error !== null && typeof error === "object" && "code" in error && error.code === "42P01") {
      return { hasExpected: false, hasAny: false };
    }
    throw error;
  } finally {
    await client.end().catch(() => {});
  }
}

/** Provision one preproduction venue + SIF and seed a sellable catalogue + a cashier. Returns the
 * five fiscal ids the server boots against. Mirrors `till-demo.ts`'s setup, minus the sale. */
async function provisionVenue(db: Database): Promise<{
  tenantId: string;
  tillId: string;
  nodeId: string;
  seriesId: string;
  locationId: string;
}> {
  const venue = await applyVenue(
    planVenue({
      country: "ES",
      taxId: "50000000K",
      legalName: "Waitron Dev SL",
      location: {
        name: "Sala principal",
        fiscalTerritory: "ES-common",
        invoiceLocales: [LOCALE],
        operationDescription: "Venta en establecimiento",
        addressLine1: "Calle Mayor 1",
        addressLine2: null,
        postalCode: "28013",
        city: "Madrid",
        province: "Madrid",
        timeZone: "Europe/Madrid",
        dayCutover: "05:00",
      },
      tillName: "Caja 1",
      seriesCode: "A",
      rectificativeSeriesCode: "R",
      admin: {
        displayName: "Administradora",
        pinHash: hashPin(ADMIN_PIN),
        passwordHash: hashPassword(ADMIN_PASSWORD),
      },
    }),
    { db },
  );

  // Seed a minimal catalogue + a cashier person as `app_user` under RLS — the same shape as
  // `till-demo.ts`, so the running till is immediately sellable (one weight product, one each
  // product, plus a cashier whose PIN the login route can verify).
  const tenantId = brandTenantId(venue.tenantId);
  await withTenant(db, tenantId, async (tx) => {
    await asAppUser(tx);
    const cat = await createCatalogue(tx, { name: "Delicatessen" });
    const comida = await createCategory(tx, { name: "Comida" });
    const bebidas = await createCategory(tx, { name: "Bebidas" });
    await createProduct(tx, {
      catalogueId: cat.id,
      categoryId: comida.id,
      descriptions: { [LOCALE]: "Jamón cortado" },
      pricingUnit: "weight",
      unitPrice: "24.90",
      vatClass: "reduced",
    });
    await createProduct(tx, {
      catalogueId: cat.id,
      categoryId: bebidas.id,
      descriptions: { [LOCALE]: "Agua mineral" },
      pricingUnit: "each",
      unitPrice: "1.50",
      vatClass: "general",
    });
    await assignCatalogueToLocation(tx, venue.locationId, cat.id);
    await tx.execute(sql`
      insert into persons (tenant_id, display_name, pin_hash, role)
      values (current_tenant_id(), 'Cajera', ${hashPin(CASHIER_PIN)}, 'staff')`);
  });

  return {
    tenantId: venue.tenantId,
    tillId: venue.tillId,
    nodeId: venue.nodeId,
    // planVenue emits the standard series first, then the rectificative one — seriesIds[0] is the
    // ordinary sale's series (the same index `till-demo.ts` reads).
    seriesId: venue.seriesIds[0]!,
    locationId: venue.locationId,
  };
}

/**
 * The idempotent bootstrap, with a fiscal safety property: it provisions a venue ONLY into a database
 * that holds none. Three cases (CLAUDE.md §5 — a second venue is a second SIF and a second hash
 * chain):
 *
 *  - the `.env` names a tenant the database still holds → REUSE it, provision nothing;
 *  - the database already holds a venue the `.env` does NOT name (a lost/stale/mismatched `.env`
 *    against a live volume) → REFUSE, directing the operator to `pnpm dev:reset`;
 *  - the database holds no venue (first run, or a freshly wiped volume) → migrate, provision one
 *    preproduction venue, seed it, and write the `.env`.
 *
 * The only sanctioned "start over" is `pnpm dev:reset`, which wipes the Docker volume (throwaway
 * preproduction data); this function never deletes data itself.
 */
export async function devSetup(opts: DevSetupOptions): Promise<DevSetupResult> {
  const { databaseUrl, envPath, log = () => {} } = opts;

  await waitForPostgres(databaseUrl, log);

  // Read the existing `.env` (if any) and ask the database, in one connection, whether it holds the
  // tenant that `.env` names and whether it holds any tenant at all.
  const existing = existsSync(envPath) ? parseEnvFile(readFileSync(envPath, "utf8")) : undefined;
  const expectedTenantId =
    existing !== undefined && isCompleteDevEnv(existing) ? existing.WAITRON_TILL_TENANT_ID : null;
  const { hasExpected, hasAny } = await inspectVenues(databaseUrl, expectedTenantId);

  // Reuse: the `.env` names a venue the database still holds.
  if (existing !== undefined && isCompleteDevEnv(existing) && hasExpected) {
    log("dev-setup: reusing the already-provisioned venue (no new fiscal chain)");
    return { reused: true, env: existing };
  }

  // Refuse: the database already holds a venue this `.env` cannot account for. Provisioning would
  // start a second fiscal chain, so fail loud rather than do it (CLAUDE.md §5).
  if (hasAny) {
    throw new Error(
      "dev-setup: the database already holds a venue, but this apps/server/.env does not name it " +
        "(missing, stale, or mismatched). Refusing to provision a second venue — it would start a new " +
        "fiscal chain. Run `pnpm dev:reset` to wipe the dev volume and re-provision from scratch.",
    );
  }

  // Fresh provision: migrate the full manifest from source (the same sets the server migrates at
  // boot — `boot.ts` uses `migrationOptionsFor(manifestSets(), config.migrationsRoot)`; `null` is
  // the from-source root, resolved to each package's own `drizzle` dir).
  log("dev-setup: migrating…");
  await applyMigrations(databaseUrl, migrationOptionsFor(manifestSets(), null));

  const db = await createPostgresDb(databaseUrl);
  let ids;
  try {
    log("dev-setup: provisioning a preproduction venue + seeding a catalogue…");
    ids = await provisionVenue(db);
  } finally {
    await db.close();
  }

  const env: DevEnv = {
    DATABASE_URL: databaseUrl,
    WAITRON_ENV: "preproduction",
    WAITRON_HTTP_PORT: "8080",
    WAITRON_CREDENTIALS_KEY: randomBytes(32).toString("base64"),
    WAITRON_CREDENTIALS_KEY_VERSION: "1",
    WAITRON_TILL_TENANT_ID: ids.tenantId,
    WAITRON_TILL_TILL_ID: ids.tillId,
    WAITRON_TILL_NODE_ID: ids.nodeId,
    WAITRON_TILL_SERIES_ID: ids.seriesId,
    WAITRON_TILL_LOCATION_ID: ids.locationId,
  };
  writeFileSync(envPath, renderEnvFile(env));
  log(`dev-setup: wrote ${envPath}`);
  return { reused: false, env };
}

/** The CLI entrypoint: resolve `apps/server/.env`, run `devSetup`, print a human summary. */
async function main(): Promise<void> {
  const envPath = fileURLToPath(new URL("../.env", import.meta.url));
  const databaseUrl =
    process.env.DATABASE_URL !== undefined && process.env.DATABASE_URL !== ""
      ? process.env.DATABASE_URL
      : DEV_DATABASE_URL;

  const result = await devSetup({
    databaseUrl,
    envPath,
    log: (line) => void console.log(line),
  });

  console.log("");
  console.log(
    result.reused
      ? "dev-setup: reused the existing venue — nothing re-provisioned."
      : "dev-setup: provisioned a fresh preproduction venue.",
  );
  console.log("");
  console.log("  till       http://localhost:5190");
  console.log("  dashboard  http://localhost:5191");
  console.log("  server     http://localhost:8080");
  console.log("");
  console.log(`  cashier PIN (till login): ${CASHIER_PIN}`);
  console.log(`  admin PIN (dashboard):    ${ADMIN_PIN}`);
  console.log("");
  console.log("Next: `pnpm dev` (or `wa-wt <worktree>`) to start all three processes.");
}

// Run only when invoked directly (`tsx scripts/dev-setup.ts`), never when imported by a test —
// the demos run `main()` on import; this must not, or importing it would spin a container.
if (
  process.argv[1] !== undefined &&
  realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))
) {
  main().catch((error: unknown) => {
    console.error("dev-setup: failed");
    console.error(error);
    process.exit(1);
  });
}
